In [15]:
import pandas as pd
from ydata_profiling import ProfileReport
import sweetviz as sv
import dtale

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dash/_jupyter.py:29: DeprecationWarning: The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.
  _dash_comm = Comm(target_name="dash")
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dash/development/component_loader.py:39: DeprecationWarning:

Dynamic components loading has been deprecated and will be removed in dash 3.0.
Update dash_daq to generate components with dash-generate-components

In [2]:
data = pd.read_csv('data/wine.csv')
display(data.head())

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
# число дегустаторов (designation)
designation_number = data['taster_name'].nunique()
display(designation_number)

19

In [4]:
# максимальная цена бутылки вина
max_price = data['price'].max()
print(max_price)

3300.0

In [5]:
data.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 12.9+ MB

In [7]:
duplicated_rows = data[data.duplicated()]
display(duplicated_rows.shape)

(9983, 13)

In [8]:
print(f'before drop: {data.shape[0]}')
print(f'after drop: {data.drop_duplicates().shape[0]}')

before drop: 129971
after drop: 119988

In [9]:
# пропуски данных
print(data.isnull().sum())

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [10]:
# удаление признаков с большим количеством пропусков
cols_to_drop = ['region_2', 'taster_twitter_handle']
data = data.drop(cols_to_drop, axis=1)

# удаление строк с пропусками
data = data.dropna(subset=['variety'])

# заполнение пропусков
data['country'] = data['country'].fillna('Unknown')
data['province'] = data['province'].fillna('Unknown')
data['region_1'] = data['region_1'].fillna('Unknown')
data['designation'] = data['designation'].fillna('Unknown')
data['taster_name'] = data['taster_name'].fillna('Unknown')

# заполнение цены медианным значением
data['price'] = data['price'].fillna(data['price'].median())

In [11]:
# пропуски данных
print(data.isnull().sum())

country        0
description    0
designation    0
points         0
price          0
province       0
region_1       0
taster_name    0
title          0
variety        0
winery         0
dtype: int64

In [12]:
# EDA одной строкой
df = pd.read_csv('data/wine.csv')
profile = ProfileReport(df, title='Wine Dataset')
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
  8%|▊         | 1/13 [00:00<00:10,  1.15it/s]
100%|██████████| 13/13 [00:04<00:00,  3.20it/s][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [13]:
report = sv.analyze(df)
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [16]:
d = dtale.show(df)
d