# Масштабирование признаков

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [2]:
data = pd.read_excel('data/data_ford_price.xlsx')

Давайте посмотрим, как StandardScaler, MinMax и RobustScaler справятся с нашими данными. Для наглядности будем использовать три столбца.

In [3]:
data = data[['price', 'year', 'weather']]
data.dropna(inplace = True)
data_scaled = data.copy()
col_names = ['price', 'weather']
x = data_scaled[col_names]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

data_scaled[col_names] = scaler.fit_transform(x.values)
data_scaled

         price  year   weather
0     2.558728  2016  0.862068
1     0.067373  2009 -0.017965
2    -1.072197  2002 -0.897998
3    -1.176990  2000 -0.395122
5    -0.677579  2003 -0.269403
...        ...   ...       ...
7012  0.682100  2015  0.862068
7013 -0.767025  2005 -0.269403
7014 -0.414149  2006  0.862068
7015 -0.335138  2011 -0.646560
7016  0.287482  2010 -0.269403

[6837 rows x 3 columns]

In [4]:
y = data_scaled['year']
x = data_scaled.drop(columns='year')

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=40)

model = LinearRegression()
model.fit(X_train, y_train)
y_predicted = model.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('MAE: %.3f' % mae)

# MAE: 3.041

MAE: 3.041

In [8]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

data_scaled[col_names] = scaler.fit_transform(x.values)
data_scaled

         price  year   weather
0     1.982455  2016  0.571429
1     0.189460  2009  0.071429
2    -0.630672  2002 -0.428571
3    -0.706090  2000 -0.142857
5    -0.346671  2003 -0.071429
...        ...   ...       ...
7012  0.631871  2015  0.571429
7013 -0.411044  2005 -0.071429
7014 -0.157084  2006  0.571429
7015 -0.100221  2011 -0.285714
7016  0.347870  2010 -0.071429

[6837 rows x 3 columns]

In [9]:
y = data_scaled['price']
x = data_scaled.drop(columns='price')

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=40)

model = LinearRegression()
model.fit(X_train, y_train)
y_predicted = model.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('MAE: %.3f' % mae)

MAE: 0.333

In [11]:
data_scaled['price'][1]

np.float64(0.1894603976017671)