In [73]:
import pandas as pd
from chardet.universaldetector import UniversalDetector
import json
from pprint import pprint
import xml.etree.ElementTree as ET

In [8]:
countries_data = pd.read_csv('data/countries.csv', sep=';')
countries_data.to_csv('data/countries.txt', index=False, sep=' ')

txt_df = pd.read_table('data/countries.txt', sep=' ', index_col=['country'])
display(txt_df)

           population      area
country
Англия          56.29    133396
Канада          38.05   9984670
США            322.28   9826630
Россия         146.24  17125191
Украина         45.50    603628
Беларусь         9.50    207600
Казахстан       17.04   2724902

РЕШАЕМ ПРОБЛЕМУ С КОДИРОВКОЙ ИСХОДНЫХ ДАННЫХ

In [11]:
error_encoding = pd.read_csv('data/ErrorEnCoding.csv', header=None, encoding_errors='replace')
display(error_encoding)

            0                           1             2
0   User_943         Accumanst@gmail.com         ������
1   User_908           Advismowr@mail.ru         ������
2   User_962             Anachso@ukr.net      ���������
3   User_973            Antecia@inbox.ru          �����
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         ������
96  User_901          V2artierso@mail.ru    �����������
97  User_970            Vashoterlo@bk.ru        �������
98  User_965         Visuareda@yahoo.com        �������
99  User_921                Aavast@ya.ru         ������

[100 rows x 3 columns]

ОПРЕДЕЛЯЕМ КОДИРОВКУ ФАЙЛА

In [15]:
detector = UniversalDetector()

with open('data/ErrorEnCoding.csv', 'rb') as f:
    for line in f:
        detector.feed(line)
        if detector.done:
            break

print(detector.close())

{'encoding': 'KOI8-R', 'confidence': 0.8773902118791048, 'language': 'Russian'}

СЧИТЫВАЕМ ФАЙЛ, УКАЗАВ КОДИРОВКУ

In [17]:
# Создаем DataFrame из файла, явно указав кодировку символов, и выводим его содержимое на экран
data = pd.read_csv('data/ErrorEnCoding.csv', encoding='koi8-r', header=None)
display(data)

            0                           1             2
0   User_943         Accumanst@gmail.com         Ижевск
1   User_908           Advismowr@mail.ru         Ижевск
2   User_962             Anachso@ukr.net      Краснодар
3   User_973            Antecia@inbox.ru          Пермь
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         Тюмень
96  User_901          V2artierso@mail.ru    Арзангелтск
97  User_970            Vashoterlo@bk.ru        Воронеж
98  User_965         Visuareda@yahoo.com        Воронеж
99  User_921                Aavast@ya.ru         Ижевск

[100 rows x 3 columns]

ЧТЕНИЕ ФАЙЛА ПО ССЫЛКЕ, ИСПОЛЬЗУЯ ФУНКЦИЮ READ_TABLE()

In [19]:
data = pd.read_table('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv', sep=',')
display(data)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

ЧТЕНИЕ/ЗАПИСЬ АРХИВИРОВАННЫХ CSV-ФАЙЛОВ

In [20]:
data = pd.read_csv('data/students_performance.zip')
display(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
# Определяем параметры архивирования — метод сжатия, имя файла в архиве
compression_opts = dict(method='zip', archive_name='out.csv')
data.to_csv('data/out.zip', index=False, compression=compression_opts)

СЧИТЫВАНИЕ ДАННЫХ ИЗ ФАЙЛА EXCEL

In [22]:
grades = pd.read_excel('data/grades.xlsx')
display(grades)

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8
5           6          Оля      9
6           7         Витя      8
7           8         Дима      7
8           9         Витя      5

СЧИТЫВАНИЕ ДАННЫХ ИЗ ФАЙЛА EXCEL ПО ССЫЛКЕ

In [23]:
data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx', skiprows=3)
display(data)

      Location  Oranges  Apples  Bananas  Blueberries  Total
0      Toronto     7651    4422     8580         3679  24332
1  Los Angeles      273    2998     9890         7293  20454
2      Atlanta     3758    6752     4599         4149  19258
3     New York     4019    8796     8486         9188  30489

In [24]:
grades = pd.read_excel('data/grades.xlsx', sheet_name='ML')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9

ВЫГРУЗКА ДАННЫХ ИЗ DATAFRAME В EXCEL-ФАЙЛ

In [25]:
# Сохраняем данные из DataFrame grades в файл grades_new.xlsx в папке data
grades.to_excel('data/grades_new.xlsx')

In [26]:
# задание 3.3
ratings_df = pd.read_excel('data/ratings_movies.xlsx', sheet_name='ratings')
display(ratings_df)

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [27]:
movies_df = pd.read_excel('data/ratings_movies.xlsx', sheet_name='movies')
display(movies_df)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [31]:
merged_df = ratings_df.merge(movies_df, on='movieId', how='left')
merged_df.to_excel('data/merged_movies.xlsx', index=False)
display(merged_df)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,1494273047,Get Out (2017),Horror
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

ОТКРЫВАЕМ JSON-ФАЙЛ

In [34]:
# Открываем файл и связываем его с объектом "f"
with open('recipes.json') as f:
    recipes = json.load(f)

# Выводим на экран содержимое переменной recipes, используя функцию pprint()
pprint(recipes)

[{'cuisine': 'greek',
  'id': 10259,
  'ingredients': ['romaine lettuce',
                  'black olives',
                  'grape tomatoes',
                  'garlic',
                  'pepper',
                  'purple onion',
                  'seasoning',
                  'garbanzo beans',
                  'feta cheese crumbles']},
 {'cuisine': 'southern_us',
  'id': 25693,
  'ingredients': ['plain flour',
                  'ground pepper',
                  'salt',
                  'tomatoes',
                  'ground black pepper',
                  'thyme',
                  'eggs',
                  'green tomatoes',
                  'yellow corn meal',
                  'milk',
                  'vegetable oil']},
 {'cuisine': 'filipino',
  'id': 20130,
  'ingredients': ['eggs',
                  'pepper',
                  'salt',
                  'mayonaise',
                  'cooking oil',
                  'green chilies',
                  'grilled chicken breasts',
                  'garlic powder',
                  'yellow onion',
                  'soy sauce',
                  'butter',
                  'chicken livers']},
 {'cuisine': 'indian',
  'id': 22213,
  'ingredients': ['water', 'vegetable oil', 'wheat', 'salt']},
 {'cuisine': 'indian',
  'id': 13162,
  'ingredients': ['black pepper',
                  'shallots',
                  'cornflour',
                  'cayenne pepper',
                  'onions',
                  'garlic paste',
                  'milk',
                  'butter',
                  'salt',
                  'lemon juice',
                  'water',
                  'chili powder',
                  'passata',
                  'oil',
                  'ground cumin',
                  'boneless chicken skinless thigh',
                  'garam masala',
                  'double cream',
                  'natural yogurt',
                  'bay leaf']},
 {'cuisine': 'jamaican',
  'id': 6602,
  'ingredients': ['plain flour',
                  'sugar',
                  'butter',
                  'eggs',
                  'fresh ginger root',
                  'salt',
                  'ground cinnamon',
                  'milk',
                  'vanilla extract',
                  'ground ginger',
                  'powdered sugar',
                  'baking powder']},
 {'cuisine': 'spanish',
  'id': 42779,
  'ingredients': ['olive oil',
                  'salt',
                  'medium shrimp',
                  'pepper',
                  'garlic',
                  'chopped cilantro',
                  'jalapeno chilies',
                  'flat leaf parsley',
                  'skirt steak',
                  'white vinegar',
                  'sea salt',
                  'bay leaf',
                  'chorizo sausage']},
 {'cuisine': 'italian',
  'id': 3735,
  'ingredients': ['sugar',
                  'pistachio nuts',
                  'white almond bark',
                  'flour',
                  'vanilla extract',
                  'olive oil',
                  'almond extract',
                  'eggs',
                  'baking powder',
                  'dried cranberries']},
 {'cuisine': 'mexican',
  'id': 16903,
  'ingredients': ['olive oil',
                  'purple onion',
                  'fresh pineapple',
                  'pork',
                  'poblano peppers',
                  'corn tortillas',
                  'cheddar cheese',
                  'ground black pepper',
                  'salt',
                  'iceberg lettuce',
                  'lime',
                  'jalapeno chilies',
                  'chopped cilantro fresh']},
 {'cuisine': 'italian',
  'id': 12734,
  'ingredients': ['chopped tomatoes',
                  'fresh basil',
                  'garlic',
                  'extra-virgin olive oil',
                  'kosher salt',
                  'flat leaf parsley']},
 {'cuisine': 'italian',
  'id': 5875,
  'ingredients': ['pimentos',
                  'sweet pepper',
                  'dried oregano',
                  'olive oil',
                  'garlic',
                  'sharp cheddar cheese',
                  'pepper',
                  'swiss cheese',
                  'provolone cheese',
                  'canola oil',
                  'mushrooms',
                  'black olives',
                  'sausages']},
 {'cuisine': 'chinese',
  'id': 45887,
  'ingredients': ['low sodium soy sauce',
                  'fresh ginger',
                  'dry mustard',
                  'green beans',
                  'white pepper',
                  'sesame oil',
                  'scallions',
                  'canola oil',
                  'sugar',
                  'Shaoxing wine',
                  'garlic',
                  'ground turkey',
                  'water',
                  'crushed red pepper flakes',
                  'corn starch']},
 {'cuisine': 'italian',
  'id': 2698,
  'ingredients': ['Italian parsley leaves',
                  'walnuts',
                  'hot red pepper flakes',
                  'extra-virgin olive oil',
                  'fresh lemon juice',
                  'trout fillet',
                  'garlic cloves',
                  'chipotle chile',
                  'fine sea salt',
                  'flat leaf parsley']},
 {'cuisine': 'mexican',
  'id': 41995,
  'ingredients': ['ground cinnamon',
                  'fresh cilantro',
                  'chili powder',
                  'ground coriander',
                  'kosher salt',
                  'ground black pepper',
                  'garlic',
                  'plum tomatoes',
                  'avocado',
                  'lime juice',
                  'flank steak',
                  'salt',
                  'ground cumin',
                  'black pepper',
                  'olive oil',
                  'crushed red pepper flakes',
                  'onions']},
 {'cuisine': 'italian',
  'id': 31908,
  'ingredients': ['fresh parmesan cheese',
                  'butter',
                  'all-purpose flour',
                  'fat free less sodium chicken broth',
                  'chopped fresh chives',
                  'gruyere cheese',
                  'ground black pepper',
                  'bacon slices',
                  'gnocchi',
                  'fat free milk',
                  'cooking spray',
                  'salt']},
 {'cuisine': 'indian',
  'id': 24717,
  'ingredients': ['tumeric',
                  'vegetable stock',
                  'tomatoes',
                  'garam masala',
                  'naan',
                  'red lentils',
                  'red chili peppers',
                  'onions',
                  'spinach',
                  'sweet potatoes']},
 {'cuisine': 'british',
  'id': 34466,
  'ingredients': ['greek yogurt',
                  'lemon curd',
                  'confectioners sugar',
                  'raspberries']},
 {'cuisine': 'italian',
  'id': 1420,
  'ingredients': ['italian seasoning',
                  'broiler-fryer chicken',
                  'mayonaise',
                  'zesty italian dressing']},
 {'cuisine': 'thai',
  'id': 2941,
  'ingredients': ['sugar', 'hot chili', 'asian fish sauce', 'lime juice']},
 {'cuisine': 'vietnamese',
  'id': 8152,
  'ingredients': ['soy sauce',
                  'vegetable oil',
                  'red bell pepper',
                  'chicken broth',
                  'yellow squash',
                  'garlic chili sauce',
                  'sliced green onions',
                  'broccolini',
                  'salt',
                  'fresh lime juice',
                  'cooked rice',
                  'chicken breasts',
                  'corn starch']},
 {'cuisine': 'thai',
  'id': 13121,
  'ingredients': ['pork loin',
                  'roasted peanuts',
                  'chopped cilantro fresh',
                  'hoisin sauce',
                  'creamy peanut butter',
                  'chopped fresh mint',
                  'thai basil',
                  'rice',
                  'medium shrimp',
                  'water',
                  'rice noodles',
                  'beansprouts']},
 {'cuisine': 'mexican',
  'id': 40523,
  'ingredients': ['roma tomatoes',
                  'kosher salt',
                  'purple onion',
                  'jalapeno chilies',
                  'lime',
                  'chopped cilantro']},
 {'cuisine': 'southern_us',
  'id': 40989,
  'ingredients': ['low-fat mayonnaise',
                  'pepper',
                  'salt',
                  'baking potatoes',
                  'eggs',
                  'spicy brown mustard']},
 {'cuisine': 'chinese',
  'id': 29630,
  'ingredients': ['sesame seeds',
                  'red pepper',
                  'yellow peppers',
                  'water',
                  'extra firm tofu',
                  'broccoli',
                  'soy sauce',
                  'orange bell pepper',
                  'arrowroot powder',
                  'fresh ginger',
                  'sesame oil',
                  'red curry paste']},
 {'cuisine': 'italian',
  'id': 49136,
  'ingredients': ['marinara sauce',
                  'flat leaf parsley',
                  'olive oil',
                  'linguine',
                  'capers',
                  'crushed red pepper flakes',
                  'olives',
                  'lemon zest',
                  'garlic']},
 {'cuisine': 'chinese',
  'id': 26705,
  'ingredients': ['sugar',
                  'lo mein noodles',
                  'salt',
                  'chicken broth',
                  'light soy sauce',
                  'flank steak',
                  'beansprouts',
                  'dried black mushrooms',
                  'pepper',
                  'chives',
                  'oyster sauce',
                  'dark soy sauce',
                  'peanuts',
                  'sesame oil',
                  'cabbage']},
 {'cuisine': 'cajun_creole',
  'id': 27976,
  'ingredients': ['herbs',
                  'lemon juice',
                  'fresh tomatoes',
                  'paprika',
                  'mango',
                  'stock',
                  'chile pepper',
                  'onions',
                  'red chili peppers',
                  'oil']},
 {'cuisine': 'italian',
  'id': 22087,
  'ingredients': ['ground black pepper',
                  'butter',
                  'sliced mushrooms',
                  'sherry',
                  'salt',
                  'grated parmesan cheese',
                  'heavy cream',
                  'spaghetti',
                  'chicken broth',
                  'cooked chicken',
                  'all-purpose flour']},
 {'cuisine': 'chinese',
  'id': 9197,
  'ingredients': ['green bell pepper',
                  'egg roll wrappers',
                  'sweet and sour sauce',
                  'corn starch',
                  'molasses',
                  'vegetable oil',
                  'oil',
                  'soy sauce',
                  'shredded cabbage',
                  'garlic',
                  'onions',
                  'fresh ginger root',
                  'ground pork',
                  'carrots']},
 {'cuisine': 'mexican',
  'id': 1299,
  'ingredients': ['flour tortillas',
                  'cheese',
                  'breakfast sausages',
                  'large eggs']},
 {'cuisine': 'italian',
  'id': 40429,
  'ingredients': ['yellow corn meal',
                  'boiling water',
                  'butter',
                  'fresh parmesan cheese',
                  'sea salt']},
 {'cuisine': 'cajun_creole',
  'id': 34419,
  'ingredients': ['chicken broth',
                  'chicken breasts',
                  'hot sauce',
                  'red bell pepper',
                  'potatoes',
                  'bacon',
                  'garlic cloves',
                  'fresh parsley',
                  'andouille sausage',
                  'cajun seasoning',
                  'peanut oil',
                  'celery',
                  'ground red pepper',
                  'all-purpose flour',
                  'shrimp',
                  'onions']},
 {'cuisine': 'mexican',
  'id': 10276,
  'ingredients': ['chili powder',
                  'crushed red pepper flakes',
                  'garlic powder',
                  'sea salt',
                  'ground cumin',
                  'onion powder',
                  'dried oregano',
                  'ground black pepper',
                  'paprika']},
 {'cuisine': 'thai',
  'id': 33465,
  'ingredients': ['eggs',
                  'shallots',
                  'firm tofu',
                  'beansprouts',
                  'turnips',
                  'palm sugar',
                  'vegetable oil',
                  'garlic cloves',
                  'sliced chicken',
                  'fish sauce',
                  'lime wedges',
                  'roasted peanuts',
                  'green papaya',
                  'chile powder',
                  'ground black pepper',
                  'tamarind paste',
                  'chinese chives']},
 {'cuisine': 'italian',
  'id': 39250,
  'ingredients': ['olive oil',
                  'onions',
                  'crushed garlic',
                  'dried oregano',
                  'green onions',
                  'white sugar',
                  'dried basil',
                  'diced tomatoes']},
 {'cuisine': 'cajun_creole',
  'id': 37963,
  'ingredients': ['olive oil',
                  'diced tomatoes',
                  'Johnsonville Andouille Dinner Sausage',
                  'parsley',
                  'shrimp',
                  'jambalaya rice mix',
                  'worcestershire sauce',
                  'hot pepper sauce',
                  'creole seasoning']},
 {'cuisine': 'italian',
  'id': 20051,
  'ingredients': ['olive oil',
                  'bread slices',
                  'great northern beans',
                  'garlic cloves',
                  'pepper',
                  'shrimp',
                  'sage leaves',
                  'salt']},
 {'cuisine': 'filipino',
  'id': 11300,
  'ingredients': ['chicken broth',
                  'cooking oil',
                  'chinese five-spice powder',
                  'ground black pepper',
                  'salt',
                  'sugar',
                  'crushed garlic',
                  'chicken thighs',
                  'soy sauce',
                  'star anise']},
 {'cuisine': 'southern_us',
  'id': 17610,
  'ingredients': ['green onions',
                  'cream cheese',
                  'shredded cheddar cheese',
                  'cayenne pepper',
                  'chili powder',
                  'garlic cloves',
                  'black-eyed peas',
                  'tortilla chips']},
 {'cuisine': 'southern_us',
  'id': 37405,
  'ingredients': ['collard greens',
                  'extra-virgin olive oil',
                  'ham hock',
                  'chicken stock',
                  'apple cider',
                  'freshly ground pepper',
                  'chile powder',
                  'bay leaves',
                  'salt',
                  'rib',
                  'light brown sugar',
                  'large garlic cloves',
                  'cayenne pepper',
                  'onions']},
 {'cuisine': 'italian',
  'id': 28302,
  'ingredients': ['Oscar Mayer Deli Fresh Smoked Ham',
                  'hoagie rolls',
                  'salami',
                  'giardiniera',
                  'mozzarella cheese',
                  'pepperoni',
                  'butter',
                  'italian seasoning']},
 {'cuisine': 'brazilian',
  'id': 31634,
  'ingredients': ['ice cubes', 'club soda', 'white rum', 'lime', 'turbinado']},
 {'cuisine': 'mexican',
  'id': 32304,
  'ingredients': ['cooked chicken',
                  'enchilada sauce',
                  'sliced green onions',
                  'picante sauce',
                  'green pepper',
                  'corn tortillas',
                  'canned black beans',
                  'shredded lettuce',
                  'sour cream',
                  'shredded cheddar cheese',
                  'garlic cloves',
                  'canola oil']},
 {'cuisine': 'indian',
  'id': 36341,
  'ingredients': ['salmon fillets',
                  'shallots',
                  'cumin seed',
                  'fresh cilantro',
                  'salt',
                  'curry powder',
                  'vegetable oil',
                  'serrano chile',
                  'fresh ginger',
                  'sauce']},
 {'cuisine': 'mexican',
  'id': 29369,
  'ingredients': ['tomatoes',
                  'chicken breast halves',
                  'chopped cilantro fresh',
                  'white vinegar',
                  'jalapeno chilies',
                  'salt',
                  'black pepper',
                  'vegetable oil',
                  'avocado',
                  'lettuce leaves',
                  'chopped onion']},
 {'cuisine': 'chinese',
  'id': 27564,
  'ingredients': ['eggs',
                  'mandarin oranges',
                  'water',
                  'orange liqueur',
                  'yellow cake mix',
                  'frosting',
                  'vegetable oil',
                  'white sugar']},
 {'cuisine': 'french',
  'id': 18515,
  'ingredients': ['sugar',
                  'salt',
                  'fennel bulb',
                  'water',
                  'lemon olive oil',
                  'grapefruit juice']},
 {'cuisine': 'southern_us',
  'id': 3335,
  'ingredients': ['sugar',
                  'all-purpose flour',
                  'vegetable oil',
                  'white cornmeal',
                  'baking powder',
                  'onions',
                  'bacon drippings',
                  'buttermilk']},
 {'cuisine': 'southern_us',
  'id': 4499,
  'ingredients': ['butter',
                  'crab boil',
                  'garlic',
                  'old bay seasoning',
                  'cream cheese',
                  'crawfish',
                  'salt']},
 {'cuisine': 'southern_us',
  'id': 4906,
  'ingredients': ['mayonaise',
                  'white sugar',
                  'ground black pepper',
                  'salt',
                  'white vinegar',
                  'lemon juice']},
 {'cuisine': 'japanese',
  'id': 5767,
  'ingredients': ['sirloin',
                  'mirin',
                  'yellow onion',
                  'low sodium soy sauce',
                  'water',
                  'corn oil',
                  'sugar',
                  'green onions',
                  'glass noodles',
                  'sake',
                  'shiitake',
                  'napa cabbage']},
 {'cuisine': 'southern_us',
  'id': 30748,
  'ingredients': ['large eggs',
                  'whipping cream',
                  'chicken broth',
                  'ground red pepper',
                  'extra sharp cheddar cheese',
                  'quickcooking grits',
                  'hot sauce',
                  'ground black pepper',
                  'worcestershire sauce',
                  'monterey jack']},
 {'cuisine': 'italian',
  'id': 35930,
  'ingredients': ['fresh basil',
                  'bay leaves',
                  'crushed red pepper',
                  'mussels',
                  'olive oil',
                  'basil',
                  'garlic cloves',
                  'black pepper',
                  'dry white wine',
                  'salt',
                  'tomatoes',
                  'finely chopped onion',
                  'linguine',
                  'flat leaf parsley']},

In [38]:
# выясним некоторые детали о блюде, которое записано первым в списке блюд
display(recipes[0]['id'])
count_ingredients = len(recipes[0]['ingredients'])
display(count_ingredients)

10259

9

In [39]:
# К какой кухне относится блюдо с id = 13121?
for recipy in recipes:
    if recipy['id'] == 13121:
        print(recipy['cuisine'])

thai

Какое количество уникальных национальных кухонь присутствуют в нашем наборе данных?

In [40]:
cousins = set()
for recipe in recipes:
    cousins.add(recipe['cuisine'])

print(f'количество уникальных кухонь: {len(cousins)}')

количество уникальных кухонь: 20

Какой из национальных кухонь принадлежит самое большое количество рецептов?

In [42]:
cousins_dishes_count = {}
for recipe in recipes:
    if recipe['cuisine'] in cousins_dishes_count:
        cousins_dishes_count[recipe['cuisine']] += 1
    else:
        cousins_dishes_count[recipe['cuisine']] = 1

print(cousins_dishes_count)
cousins_dishes_count = sorted(cousins_dishes_count.items(), key=lambda x: x[1], reverse=True)
print(cousins_dishes_count[0])

{'greek': 15, 'southern_us': 52, 'filipino': 11, 'indian': 41, 'jamaican': 6, 'spanish': 12, 'italian': 101, 'mexican': 79, 'chinese': 39, 'british': 9, 'thai': 17, 'vietnamese': 9, 'cajun_creole': 16, 'brazilian': 3, 'french': 25, 'japanese': 24, 'irish': 9, 'korean': 21, 'moroccan': 9, 'russian': 2}
('italian', 101)

ИЗ JSON В PANDAS

In [51]:
df = pd.DataFrame(recipes)
display(df)

        id      cuisine                                        ingredients
0    10259        greek  [romaine lettuce, black olives, grape tomatoes...
1    25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2    20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3    22213       indian                [water, vegetable oil, wheat, salt]
4    13162       indian  [black pepper, shallots, cornflour, cayenne pe...
..     ...          ...                                                ...
495   1121      chinese  [ground pepper, garlic, safflower oil, green o...
496  18376      italian  [penne, garlic, eggplant, lemon juice, olive o...
497  17815      italian  [cold water, dry white wine, fish fillets, cho...
498  32878  southern_us  [water, cajun seasoning, yellow onion, shrimp,...
499  24410      british  [mint, large eggs, heavy cream, berries, groun...

[500 rows x 3 columns]

Создайте реестр уникальных ингредиентов all_ingredients, который будет использоваться на втором этапе.

In [52]:
ingredients_list = df['ingredients'].tolist()
ingredients_set = set()
for ingredients in ingredients_list:
    for ingredient in ingredients:
        ingredients_set.add(ingredient)

print(ingredients_set)
print(len(ingredients_set))

{'cucumber', 'ham hock', 'dried rosemary', 'chile powder', 'fresh lime', 'sugar', 'ricotta', 'Himalayan salt', 'cardamom', 'bell pepper', 'nori', 'dry vermouth', 'mace', 'plain whole-milk yogurt', 'coconut', 'whole milk ricotta cheese', 'marshmallow creme', 'semisweet chocolate', 'pitted kalamata olives', 'ras el hanout', 'oil cured olives', 'peanut sauce', 'coriander', 'ancho chile pepper', 'mini cucumbers', 'veal cutlets', 'nonfat milk', 'eau de vie', 'jaggery', 'kale', 'frozen whole kernel corn', 'greens', 'goat cheese', 'large egg whites', 'chili paste', 'taco sauce', 'Old El Paso Flour Tortillas', 'bertolli vineyard premium collect marinara with burgundi wine sauc', 'Shaoxing wine', 'tuna fillets', 'wheat bran', 'grilled chicken breasts', 'serrano ham', 'szechwan peppercorns', 'lime', 'dill', 'champagne vinegar', 'Turkish bay leaves', 'mixed spice', 'peeled tomatoes', 'pickled jalapeno peppers', 'bok choy', 'tamarind', 'confectioners sugar', 'chestnut flour', 'corn starch', 'store bought low sodium chicken stock', 'smoked paprika', 'kiwi', 'whipping cream', 'back bacon rashers', 'pimentos', 'romaine lettuce', 'thai green curry paste', 'canola oil', 'crawfish', 'stuffing', 'star anise', 'balsamic vinegar', 'rice noodles', 'green beans', 'bread', 'luke warm water', 'wheat germ', 'cheese ravioli', 'garlic powder', 'pickles', 'bosc pears', 'ricotta cheese', 'coarse salt', 'cremini mushrooms', 'fat skimmed chicken broth', 'light brown muscavado sugar', 'sunflower oil', 'chicken breasts', 'chicken', 'penne', 'chili oil', 'soppressata', 'fat-free refried beans', 'epazote', 'country ham', 'dried cherry', 'dried shiitake mushrooms', 'pasta sauce', 'dried basil', 'golden delicious apples', 'orange juice concentrate', 'lasagne', 'dried bonito flakes', 'ground flaxseed', 'wasabi', 'prepared horseradish', 'extra large eggs', 'wheat', 'lasagna noodles', 'sweet paprika', 'dri leav thyme', 'sirloin tip roast', 'ground beef', '1% low-fat milk', 'hazelnut oil', 'ciabatta', 'dashi kombu', 'ketchup', 'arborio rice', 'pita bread rounds', 'grated parmesan cheese', 'mandarin oranges', 'branzino fillets', 'crushed garlic', 'couscous', 'caster', 'egg yolks', 'soft fresh goat cheese', 'cinnamon graham crackers', 'bread crumb fresh', 'egg noodles', 'white sandwich bread', 'Tabasco Pepper Sauce', 'vanilla lowfat yogurt', 'ground nutmeg', 'louisiana hot sauce', 'green cardamom pods', 'portabello mushroom', 'cheese slices', 'white radish', 'margarita salt', 'rice vinegar', 'seasoned rice wine vinegar', 'swiss cheese', 'yellow crookneck squash', 'olive oil flavored cooking spray', 'baking potatoes', 'chopped walnuts', 'saltines', 'boneless chop pork', 'quail', 'applewood smoked bacon', 'cracked black pepper', 'frozen broad beans', 'ground lamb', 'basmati rice', 'semolina', 'top round steak', 'chopped nuts', 'dinner rolls', 'fire roasted diced tomatoes', 'fresh coriander', 'fennel', 'vegetable juice', 'ricotta salata', 'hot red pepper flakes', 'fruit', 'beef', 'asiago', 'anchovy fillets', 'mustard oil', 'lean ground pork', 'active dry yeast', 'taco seasoning', 'chunky salsa', 'light soy sauce', 'eggs', 'Italian parsley leaves', 'garbanzo beans', 'smoked streaky bacon', 'hominy', 'shredded lettuce', 'sundried tomato paste', 'celery salt', 'ramps', 'arame', 'guajillo', 'jam', 'safflower oil', 'roasted red peppers', 'flax seed meal', 'clams', 'mushroom powder', 'vegetable oil', 'spinach leaves', 'half & half', 'organic sugar', 'Flora Cuisine', 'moong dal', 'sweet pepper', 'Japanese soy sauce', 'vermicelli', 'sesame oil', 'dried chile', 'bread slices', 'granny smith apples', 'bone-in chicken breasts', 'bread crumbs', 'ground cinnamon', 'dijon mustard', 'bamboo shoots', 'rubbed sage', 'ground chicken', 'chicken cutlets', 'whole milk', 'boiling potatoes', 'peppercorns', 'basil leaves', 'sliced black olives', 'grape tomatoes', 'crushed red pepper', 'boneless skinless chicken breast halves', 'lean steak', 'tuna', 'taco seasoning mix', 'hot chili', 'thai chile', 'Sriracha', 'jumbo shrimp', 'dry mustard', 'chicken drumsticks', 'baby carrots', 'sun-dried tomatoes in oil', 'grated orange peel', 'dried chickpeas', 'haricots verts', 'shell-on shrimp', 'vegetable oil cooking spray', 'kasuri methi', 'white vinegar', 'allspice berries', 'dried chile peppers', 'dry bread crumbs', 'boneless chicken breast', 'kahlГєa', 'chickpea flour', 'dried oregano', 'fenugreek seeds', 'fresh thyme leaves', 'pork', 'black mustard seeds', 'crema mexicana', 'vegan margarine', 'vidalia', 'ground allspice', 'spareribs', 'italian seasoning mix', 'yellow peppers', 'crab meat', 'hot water', 'garlic chili sauce', 'chocolate covered coffee beans', 'pickled carrots', 'lower sodium soy sauce', 'chile pepper', 'lettuce', 'watercress', 'pecorino cheese', 'sliced mushrooms', 'red wine vinegar', 'dried currants', 'gnocchi', 'crГЁme fraГ®che', 'meat bones', 'freshly ground pepper', 'all-purpose flour', 'leg of lamb', 'straw mushrooms', 'guacamole', 'Johnsonville Andouille Dinner Sausage', 'chickpeas', 'starchy potatoes', 'dried red chile peppers', 'green peas', 'noodles', 'pesto', 'adobo sauce', 'linguine', 'soba', 'SargentoВ® Traditional Cut Shredded Mozzarella Cheese', 'erythritol', 'ancho powder', 'water chestnuts', 'chicken livers', 'chipotle chile', 'pickled jalapenos', 'table cream', 'fried garlic', 'curry powder', 'pork shoulder', 'cannellini beans', 'chives', 'white wine vinegar', 'pepperoni', 'milk', 'chicken legs', 'mexican chorizo', 'dried dillweed', 'green chilies', 'club soda', 'trout fillet', 'large eggs', 'kimchi', 'parsnips', 'andouille sausage links', 'molasses', 'miso paste', 'cabbage', 'boneless skinless chicken breasts', 'boneless skinless chicken', 'sesame salt', 'natural yogurt', 'grating cheese', 'serrano', 'red beans', 'creamy peanut butter', 'manchego cheese', 'peanut butter', 'chile sauce', 'asian pear', '(    oz.) tomato sauce', 'long grain white rice', 'Italian seasoned breadcrumbs', 'jicama', 'white bread', 'french bread', 'crushed tomatoes', 'rock sugar', 'mint', 'hazelnuts', 'red enchilada sauce', 'mozzarella balls', 'smoked ham hocks', 'garam masala', 'fennel bulb', 'food colouring', 'mascarpone', 'butter lettuce', 'yellow corn meal', 'short rib', 'chestnuts', 'fenugreek', 'instant espresso powder', 'aioli', 'barley', 'romano cheese', 'urad dal', 'veal chops', 'coconut sugar', 'porcini', 'brie cheese', 'baby spinach leaves', 'fontina', 'mustard greens', 'chicken stock', 'garlic salt', 'instant white rice', 'water chestnuts, drained and chopped', 'quinoa', 'pizza crust', 'plum tomatoes', 'shredded Monterey Jack cheese', 'shredded cabbage', 'roasted peanuts', 'Gochujang base', 'pinenuts', 'ground meat', 'Philadelphia Cream Cheese', 'swiss chard', 'Madeira', 'dark rum', 'double-acting baking powder', 'pork ribs', 'wood ear mushrooms', 'orzo pasta', 'tamarind pulp', 'pecan halves', 'corn kernels', 'dark brown sugar', 'brown sugar', 'vine ripened tomatoes', 'chicken bouillon', 'baking powder', 'chile paste', 'glass noodles', 'boiling water', 'sweet potatoes', 'egg bread', 'shrimp and crab boil seasoning', 'italian salad dressing mix', 'Taiwanese bok choy', 'green chile', 'enchilada sauce', 'Mexican beer', 'fry mix', 'stock', 'mushrooms', 'hoisin sauce', 'greek yogurt', 'serrano chile', 'red pepper flakes', 'chipotle chile powder', 'ground white pepper', 'thyme', 'chili flakes', 'sauce', 'broiler-fryer chicken', 'allspice', 'cumin', 'lo mein noodles', 'chinese cabbage', 'florets', 'unsweetened cocoa powder', 'fresh red chili', 'boneless chicken thighs', 'solid pack pumpkin', 'fresh lime juice', 'matcha green tea powder', 'pitted olives', 'cooked rice', 'fettucine', 'pecans', 'cheddar cheese', 'fresh rosemary', 'worcestershire sauce', 'fresh veget', 'fresh tarragon', 'chicken breast halves', 'sherry', 'evaporated milk', 'chopped pecans', 'capers', 'medjool date', 'vegetables', 'fat-free cottage cheese', 'green cardamom', 'sourdough', 'steamed white rice', 'tomato paste', 'annatto oil', 'gari', 'black bean sauce', 'sambal ulek', 'red bell pepper', 'cauliflower flowerets', 'palm sugar', 'kaffir lime leaves', 'lower sodium chicken broth', 'salsa', 'old bay seasoning', 'powdered sugar', 'bay leaves', 'sesame paste', 'cumin seed', 'orzo', 'dry red wine', 'grate lime peel', 'gluten-free tamari', 'yellow squash', 'refrigerated piecrusts', 'apple cider', 'red radishes', 'red chili powder', 'buttermilk', 'spicy brown mustard', 'kale leaves', 'saffron', 'kashmiri chile', 'cooked brown rice', 'sweet cherries', 'potatoes', 'parsley', 'extra firm tofu', 'chipotle', 'cane sugar', 'whole kernel corn, drain', 'beansprouts', 'water', 'pearl barley', 'dashi', 'olive oil cooking spray', 'brown mustard seeds', 'cake flour', 'finely chopped fresh parsley', 'golden brown sugar', 'seasoned bread crumbs', 'cracker crumbs', 'fat', 'low-fat sour cream', 'coconut cream', 'pasta', 'BertolliВ® Classico Olive Oil', 'white sugar', 'lemon olive oil', 'cream cheese, soften', 'garlic paste', 'dark soy sauce', 'spinach', 'green pepper', 'raisins', 'jack cheese', 'fish sauce', 'Italian bread', 'zucchini', 'fresh asparagus', 'tomatoes', 'lard', 'glutinous rice flour', 'grated orange', 'boneless pork loin', 'blackberries', 'galangal', 'softened butter', 'baking apples', 'arrowroot powder', 'part-skim ricotta cheese', 'pears', 'condensed cream of chicken soup', 'fresh ginger', 'boneless rib eye steaks', 'egg roll wraps', 'baby bok choy', 'seasoning salt', 'gingerroot', 'bread flour', 'red miso', 'smoked trout', 'asparagus', 'grated lemon zest', 'cooking oil', 'coconut milk', 'tahini', 'wasabi paste', 'fat-free mayonnaise', 'fresh mushrooms', 'basil pesto sauce', 'apple cider vinegar', 'crusty rolls', 'frozen edamame beans', 'bone in chicken thighs', 'ground pepper', 'salsa verde', 'unsalted roasted peanuts', 'large shrimp', 'gingersnap', 'sun-dried tomatoes', 'hot sauce', 'rose petals', 'onion tops', 'preserved lemon', 'whole wheat pasta', 'tomato sauce', 'red cabbage', 'ice', 'string beans', 'goji berries', 'lemon curd', 'unsalted butter', 'orange', 'ground ginger', 'nonstick spray', 'eggplant', 'McCormick Parsley Flakes', 'espresso', 'reduced sodium soy sauce', 'clove', 'ham', 'fresh parsley', 'crusty bread', 'granulated garlic', 'nutmeg', 'kefalotyri', 'lime juice', 'extra sharp cheddar cheese', 'lemongrass', 'tumeric', 'unsalted dry roast peanuts', 'daikon', 'penne pasta', 'ground coriander', 'brown cardamom', 'phyllo', 'creole mustard', 'rice paper', 'sage leaves', 'wonton wrappers', 'yellow cake mix', 'chinese five-spice powder', 'short-grain rice', 'grana padano', 'fillets', 'orange liqueur', 'apricot preserves', 'great northern beans', 'broccolini', 'non-fat sour cream', 'lettuce leaves', 'grated jack cheese', 'chipotles in adobo', 'low sodium chicken broth', 'panko breadcrumbs', 'chicken wings', 'mustard', 'flat leaf parsley', 'finely chopped onion', 'pork loin chops', 'chopped cilantro fresh', 'tofu', 'karashi', 'fresh basil', 'fresh ginger root', 'plain yogurt', 'red lentils', 'pork chops', 'condiments', 'lamb', 'apples', 'lemon', 'kalamata', 'oregano', 'red chile powder', 'parmigiano reggiano cheese', 'burger buns', 'parmesan cheese', 'carrots', 'filet', 'seafood seasoning', 'polenta', 'baby arugula', 'fat free cream cheese', 'sliced chicken', 'skim milk', 'berries', 'penne rigate', 'grouper', 'wakame', 'seasoning', 'oyster sauce', 'orange zest', 'yellow mustard', 'cactus pad', 'artichokes', 'dough', 'rum extract', 'rhubarb', 'golden raisins', 'lemon slices', 'Fuyu persimmons', 'chiles', 'sheepвЂ™s milk cheese', 'grapeseed oil', 'tapioca starch', 'natural peanut butter', 'onions', 'chopped green chilies', 'canned corn', 'cooked quinoa', 'roasted salted cashews', 'torn romain lettuc leav', 'chili pepper', 'mixed greens', 'kidney beans', 'membrillo', 'potato starch', 'curry', 'salad', 'beer', 'free range egg', 'white almond bark', 'lean ground beef', 'firmly packed brown sugar', 'peanut oil', 'paprika', 'Crystal Farms Shredded Gouda Cheese', 'reduced fat milk', 'green peppercorns', 'corn flour', 'frozen blueberries', 'cooked shrimp', 'chicken leg quarters', 'butter', 'green onions', 'jasmine rice', 'part-skim mozzarella cheese', 'bean paste', 'dry white wine', 'oven-ready lasagna noodles', 'chinese noodles', 'marshmallows', 'low-fat buttermilk', 'fat free less sodium chicken broth', 'demerara sugar', 'cashew nuts', 'pico de gallo', 'beef shank', 'corn syrup', 'coconut flour', 'green bell pepper, slice', 'crema', 'shredded mozzarella cheese', 'rice cakes', 'tamari soy sauce', 'sourdough loaf', 'fish fillets', 'maida flour', 'hamburger buns', 'red pepper', 'fresh parmesan cheese', 'grapefruit juice', 'boiled ham', 'beef stock', 'beef rib short', 'corn tortillas', 'tomato purГ©e', 'fresh lemon juice', 'naan', 'garlic cloves', 'lemon grass', 'whole nutmegs', 'rosemary leaves', 'pasta rotel', 'salted roast peanuts', 'toasted pecans', 'white rice', 'catfish fillets', 'horseradish', 'pumpkin purГ©e', 'blueberri preserv', 'honey', 'cider vinegar', 'plain breadcrumbs', 'shortening', 'sherry vinegar', 'peaches', 'bittersweet chocolate', 'condensed cheddar cheese soup', 'roma tomatoes', 'duck fat', 'chopped tomatoes', 'black peppercorns', 'rolls', 'poblano chiles', 'cheese', 'savoy cabbage', 'refried beans', 'superfine sugar', 'calimyrna figs', 'grated nutmeg', 'english muffins, split and toasted', 'broccoli rabe', 'mango', 'freshly grated parmesan', 'soba noodles', 'asian fish sauce', 'garlic puree', 'steak', 'ice cubes', 'pistachio nuts', 'dark sesame oil', 'leaves', 'chili garlic paste', 'lump crab meat', 'fresh herbs', 'fresh tomatoes', 'sprinkles', 'reduced sodium chicken broth', 'tortilla chips', 'peeled fresh ginger', 'cinnamon sugar', 'chili powder', 'cayenne', 'lemon juice', 'cream of tartar', 'lentils', 'double cream', 'Mexican cheese', 'cinnamon', 'frozen spinach', 'spaghetti', 'genoa salami', 'lamb neck fillets', 'strawberries', 'turnips', 'condensed cream of mushroom soup', 'feta cheese', 'curry leaves', 'lime wedges', 'chicken bones', 'lemon soda', 'mustard powder', 'cherry tomatoes', 'vidalia onion', 'reduced sodium tamari', 'fat free yogurt', 'caramel sauce', 'figs', 'parsley leaves', 'cream', 'low sodium soy sauce', 'coleslaw', 'skirt steak', 'baguette', 'dried mint flakes', 'creole seasoning', 'edamame', 'low-fat mayonnaise', 'thai basil', 'baby potatoes', 'pistachios', 'black beans', 'gruyere cheese', 'skinless chicken breasts', 'vinaigrette dressing', 'plantains', 'instant butterscotch pudding mix', 'bacon slices', 'scallions', 'silken tofu', 'pork loin', 'vegetable broth', 'toasted sesame oil', 'heavy whipping cream', 'napa cabbage leaves', 'fresh salmon', 'basil', 'capicola', 'sausage casings', 'amchur', 'canned black beans', 'fingerling potatoes', 'pineapple juice', 'wide rice noodles', 'white cornmeal', 'pitas', 'baking soda', 'rosemary sprigs', 'spring onions', 'chili', 'hibiscus', 'giardiniera', 'english cucumber', 'tequila', 'spam', 'snow peas', 'octopuses', 'seaweed', 'pasta water', 'marinara sauce', 'bacon, crisp-cooked and crumbled', 'almond extract', 'fresh pineapple', 'chillies', 'extra-lean ground beef', 'bay leaf', 'capsicum', 'summer squash', 'candied orange peel', 'chuck roast', 'margarita mix', 'granulated sugar', 'almonds', 'yukon gold potatoes', 'aged gouda', 'fresh raspberries', 'chinese chives', 'diced celery', 'sea scallops', 'beans', 'chees fresco queso', 'dried porcini mushrooms', 'picante sauce', 'canned low sodium chicken broth', 'oysters', 'fresh thyme', 'shiso', 'whole wheat flour', 'kecap manis', 'coriander powder', 'okra', 'chunky peanut butter', 'vinegar', 'fenugreek leaves', 'flour', 'tomato ketchup', 'organic chicken', 'bird chile', 'white wine', 'cooking wine', 'collard greens', 'chopped celery', 'chopped green bell pepper', 'minced beef', 'low-fat natural yogurt', 'coarse sea salt', 'vanilla extract', 'rib eye steaks', 'heavy cream', 'low-fat milk', 'monterey jack', 'medium eggs', 'persian cucumber', 'frozen peas', 'bourbon whiskey', 'white miso', 'navy beans', 'chopped fresh sage', 'butternut squash', 'fresh dill', 'maple syrup', 'oil', 'fresh oregano', 'cooked ham', 'California bay leaves', 'colby cheese', 'lime zest', 'russet potatoes', 'pork shoulder roast', 'cod', 'frozen pastry puff sheets', 'warm water', 'coffee beans', 'rice syrup', 'jambalaya rice mix', 'yoghurt', 'sweet and sour sauce', 'chorizo', 'green tomatoes', 'anise', 'pasilla pepper', 'tamarind paste', 'pepper', 'dried kidney beans', 'plain flour', 'green papaya', 'red wine', 'pound cake', 'Thai fish sauce', 'tortillas', 'dressing', 'mozzarella cheese', 'chicken tenderloin', 'buckwheat noodles', 'frozen whipped topping', 'Pillsburyв„ў Refrigerated Crescent Dinner Rolls', 'self rising flour', 'ginger', 'fresh lemon', 'ground cloves', 'pickapeppa sauce', 'cauliflower', 'fat free milk', 'fresh spinach', 'Old El Pasoв„ў mild red enchilada sauce', 'piloncillo', 'toasted cashews', 'cayenne pepper', 'lemon zest', 'black olives', 'arugula', 'italian seasoning', 'rice wine', 'cornflour', 'kosher salt', 'white corn tortillas', 'celery', 'sweet onion', 'coconut vinegar', 'chili paste with garlic', 'lemon cucumber', 'cooked chicken', 'button mushrooms', 'tea bags', 'chipotle peppers', 'provolone cheese', 'red beets', 'chili sauce', 'onion powder', 'flank steak', 'sweetened condensed milk', 'orange bell pepper', 'zesty italian dressing', 'white onion', 'red chili peppers', 'barbecue sauce', 'red kidney beans', 'leeks', 'coarse kosher salt', 'salmon steaks', 'wish bone guacamol ranch dress', 'Crystal Farms Butter', 'chopped cilantro', 'garlic', 'hot pepper sauce', 'shrimp', 'grated GruyГЁre cheese', 'white sesame seeds', 'tomatillo salsa', 'bottled clam juice', 'kielbasa', 'jamaican jerk season', 'kalonji', 'bacon drippings', 'dried tart cherries', 'chinese rice wine', 'celery ribs', 'duck breast halves', 'light pancake syrup', 'saffron threads', 'quickcooking grits', 'pesto sauce', 'duck', 'unflavored gelatin', 'demi-glace', 'frozen corn', 'chopped parsley', 'hoagie rolls', 'shredded carrots', 'chocolate instant pudding', 'ginger paste', 'brine-cured black olives', 'manicotti shells', 'confit', 'white pepper', 'yellow bell pepper', 'rice flour', 'slivered almonds', 'chocolate sauce', 'hearts of palm', 'yellow onion', 'refrigerated crescent rolls', 'thyme leaves', 'chopped onion', 'salt and ground black pepper', 'curry paste', '2% reduced-fat milk', 'sliced almonds', 'pecorino romano cheese', 'fresh leav spinach', 'ghee', 'tuna steaks', 'ground veal', 'boneless beef short ribs', 'fresh bay leaves', 'cauliflower florets', 'sharp cheddar cheese', 'chocolate morsels', 'round steaks', 'hass avocado', 'puff pastry', 'black salt', 'unsweetened coconut milk', 'sliced green onions', 'feta cheese crumbles', 'purple onion', 'Korean chile flakes', 'dry sherry', 'chorizo sausage', 'instant espresso', 'lager beer', 'sour cream', 'cajun seasoning', 'minced garlic', 'sake', 'andouille sausage', 'turnip greens', 'bacon', 'shredded cheese', 'Mexican cheese blend', 'pickled vegetables', 'chopped fresh mint', 'shredded sharp cheddar cheese', 'brewed tea', 'steel-cut oats', 'Smithfield Ham', 'iceberg lettuce', 'crabmeat', 'coconut oil', 'tomatillos', 'chorizo spanish', 'medium shrimp', 'myzithra', 'cooked white rice', 'almond flour', 'red kidnei beans, rins and drain', 'boneless center cut pork chops', 'fine sea salt', 'jalapeno chilies', 'toasted sesame seeds', 'breakfast sausages', 'masa harina', 'corn oil', 'fennel seeds', 'sweet chili sauce', 'green curry paste', 'large egg yolks', 'frosting', 'walnuts', 'chopped garlic', 'caul fat', 'turbinado', 'okra pods', 'diced bell pepper', 'plum sauce', 'corn', 'shredded cheddar cheese', 'drumstick', 'cilantro leaves', 'cinnamon sticks', 'coconut aminos', 'pineapple preserves', 'ground black pepper', 'egg whites', 'salted butter', 'napa cabbage', 'passata', 'cooking spray', 'mint leaves', 'instant espresso granules', 'chicken thighs', 'yellowtail', 'liquid', 'prawns', 'wh

Теперь определим функцию contains(), с помощью которой мы будем проверять наличие конкретного ингредиента ingredient_name в рецепте текущего блюда, который представлен списком ingredient_list (значение в ячейке столбца ingredients текущего рецепта).

In [47]:
# Определяем имя функции и передаваемые аргументы
def contains(ingredient_list):
    # Если ингредиент есть в текущем блюде,
    if ingredient_name in ingredient_list:
        # возвращаем значение 1
        return 1
    # Если ингредиента нет в текущем блюде,
    else:
        # возвращаем значение 0
        return 0

In [54]:
for ingredient_name in ingredients_set:
    df[ingredient_name] = df['ingredients'].apply(contains)
display(df)

/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient_name] = df['ingredients'].apply(contains)
/var/folders/70/p1sc01nn2_92vgfrfd9_m6640000gn/T/ipykernel_22287/1020068534.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

,id,cuisine,ingredients,cucumber,ham hock,dried rosemary,chile powder,fresh lime,sugar,ricotta,...,light sour cream,ranch dressing,egg roll wrappers,crab boil,grated lemon peel,roasted garlic,fresh basil leaves,unsalted cashews,frozen chopped spinach,mayonaise
0,10259,greek,"[romaine lettuce, black olives, grape tomatoes...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,"[plain flour, ground pepper, salt, tomatoes, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,"[eggs, pepper, salt, mayonaise, cooking oil, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,22213,indian,"[water, vegetable oil, wheat, salt]",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,"[black pepper, shallots, cornflour, cayenne pe...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,"[ground pepper, garlic, safflower oil, green o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,18376,italian,"[penne, garlic, eggplant, lemon juice, olive o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,17815,italian,"[cold water, dry white wine, fish fillets, cho...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,32878,southern_us,"[water, cajun seasoning, yellow onion, shrimp,...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,24410,british,"[mint, large eggs, heavy cream, berries, groun...",0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [55]:
# Заменяем список ингредиентов в рецепте на их количество
df['ingredients'] = df['ingredients'].apply(len)
# Выводим содержимое полученного DataFrame на экран
display(df)

,id,cuisine,ingredients,cucumber,ham hock,dried rosemary,chile powder,fresh lime,sugar,ricotta,...,light sour cream,ranch dressing,egg roll wrappers,crab boil,grated lemon peel,roasted garlic,fresh basil leaves,unsalted cashews,frozen chopped spinach,mayonaise
0,10259,greek,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,22213,indian,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,18376,italian,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,17815,italian,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,32878,southern_us,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,24410,british,17,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

СОХРАНЯЕМ DATAFRAME В CSV-ФАЙЛЕ

In [56]:
df.to_csv('recipes.csv', index = False)

Решим обратную задачу и создадим JSON-файл из сохранённого ранее CSV-файла, который получили в конце предыдущего этапа
Начнём с чтения файла и создания DataFrame на его основе:

In [59]:
# Создаём DataFrame, читаем данные из файла в переменную df
df = pd.read_csv('recipes.csv')
display(df)
ids = df['id'].unique().tolist()
display(ids)

,id,cuisine,ingredients,cucumber,ham hock,dried rosemary,chile powder,fresh lime,sugar,ricotta,...,light sour cream,ranch dressing,egg roll wrappers,crab boil,grated lemon peel,roasted garlic,fresh basil leaves,unsalted cashews,frozen chopped spinach,mayonaise
0,10259,greek,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,22213,indian,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,18376,italian,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,17815,italian,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,32878,southern_us,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,24410,british,17,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

[10259,
 25693,
 20130,
 22213,
 13162,
 6602,
 42779,
 3735,
 16903,
 12734,
 5875,
 45887,
 2698,
 41995,
 31908,
 24717,
 34466,
 1420,
 2941,
 8152,
 13121,
 40523,
 40989,
 29630,
 49136,
 26705,
 27976,
 22087,
 9197,
 1299,
 40429,
 34419,
 10276,
 33465,
 39250,
 37963,
 20051,
 11300,
 17610,
 37405,
 28302,
 31634,
 32304,
 36341,
 29369,
 27564,
 18515,
 3335,
 4499,
 4906,
 5767,
 30748,
 35930,
 44902,
 31119,
 3535,
 47028,
 38112,
 2646,
 5206,
 38233,
 39267,
 11913,
 20591,
 70,
 43928,
 8530,
 275,
 43769,
 49111,
 11886,
 45839,
 699,
 24568,
 8820,
 16582,
 9058,
 4715,
 29061,
 2107,
 22825,
 13758,
 6886,
 14874,
 43399,
 38254,
 41596,
 33989,
 17004,
 4969,
 31831,
 46648,
 36888,
 34471,
 25164,
 39600,
 46357,
 46905,
 8753,
 37337,
 17636,
 8997,
 28851,
 4635,
 7782,
 8031,
 49434,
 31318,
 31027,
 47095,
 4574,
 19757,
 35570,
 44812,
 27858,
 18624,
 9406,
 35132,
 33071,
 8321,
 20955,
 45776,
 6043,
 336,
 25751,
 793,
 34367,
 7406,
 7473,
 7532,
 5924,
 5802,
 41078,
 20665,
 39471,
 9595,
 27869,
 44776,
 17771,
 43970,
 27165,
 11190,
 21872,
 29853,
 1154,
 9069,
 46975,
 4892,
 21467,
 20919,
 42013,
 17821,
 44138,
 5980,
 41961,
 27008,
 31867,
 34248,
 13792,
 38502,
 7023,
 7783,
 2472,
 45193,
 7501,
 34930,
 42967,
 14080,
 45352,
 46205,
 47427,
 40064,
 9010,
 18611,
 35124,
 45605,
 16334,
 32035,
 16810,
 3641,
 43374,
 9112,
 14970,
 41396,
 4748,
 41833,
 18031,
 29734,
 26415,
 29801,
 24351,
 8480,
 27023,
 10425,
 37188,
 24338,
 3457,
 1355,
 40738,
 42380,
 16857,
 2923,
 7528,
 15990,
 27615,
 26061,
 23053,
 5090,
 36862,
 873,
 23726,
 48576,
 25118,
 17586,
 22678,
 428,
 6745,
 31009,
 20983,
 19572,
 15273,
 14198,
 18643,
 17816,
 46893,
 1110,
 21375,
 42833,
 5328,
 17188,
 19622,
 26498,
 27140,
 32353,
 37070,
 2298,
 15291,
 8274,
 23521,
 28342,
 8791,
 242,
 15347,
 20981,
 39391,
 23147,
 44020,
 3245,
 40403,
 33603,
 19691,
 6862,
 20123,
 22712,
 31428,
 9373,
 7666,
 40617,
 26676,
 38067,
 14778,
 636,
 35408,
 22658,
 44866,
 18389,
 40014,
 20863,
 35041,
 30649,
 14351,
 14146,
 48911,
 4252,
 46135,
 20668,
 4009,
 40466,
 32480,
 8223,
 4114,
 3605,
 41363,
 23437,
 9291,
 45423,
 31462,
 45412,
 33048,
 42879,
 6164,
 37704,
 29489,
 6115,
 9829,
 36254,
 23839,
 40283,
 11108,
 42685,
 23629,
 36565,
 42083,
 26032,
 19811,
 30382,
 49175,
 41668,
 9206,
 7322,
 23637,
 43650,
 45593,
 38706,
 38433,
 47826,
 7171,
 18231,
 34385,
 12340,
 33221,
 43228,
 3416,
 23636,
 22822,
 801,
 42007,
 20792,
 44500,
 19004,
 41301,
 16712,
 28250,
 34209,
 1667,
 48571,
 10074,
 43711,
 6440,
 36583,
 10003,
 24738,
 20039,
 29446,
 45711,
 45039,
 46417,
 48080,
 15882,
 49263,
 45956,
 40509,
 11665,
 22997,
 44271,
 29887,
 1764,
 40300,
 45296,
 24365,
 34996,
 47623,
 26464,
 18329,
 43437,
 25375,
 26631,
 26172,
 19747,
 38346,
 31903,
 12099,
 38717,
 30335,
 15171,
 31425,
 36118,
 18190,
 33717,
 15460,
 21052,
 35729,
 45841,
 1182,
 15229,
 31209,
 18271,
 14202,
 10111,
 1128,
 37109,
 9952,
 11164,
 9852,
 45574,
 22581,
 9082,
 30985,
 42612,
 38754,
 45037,
 33197,
 13005,
 18203,
 10210,
 38581,
 32489,
 26647,
 34240,
 8579,
 49639,
 17120,
 27213,
 18621,
 35302,
 27648,
 17658,
 24029,
 45990,
 20692,
 37593,
 46635,
 20149,
 623,
 12048,
 48523,
 16797,
 23336,
 15645,
 39904,
 35962,
 9138,
 47406,
 30250,
 26545,
 13554,
 44562,
 3820,
 49668,
 27688,
 31969,
 33085,
 20061,
 24552,
 27204,
 8304,
 28063,
 38473,
 84,
 12152,
 25201,
 22633,
 41282,
 3040,
 29033,
 40224,
 24640,
 49262,
 28657,
 18842,
 27019,
 2982,
 33222,
 39361,
 13489,
 36461,
 20757,
 35136,
 30327,
 43455,
 36947,
 28056,
 7530,
 47505,
 16520,
 35311,
 22833,
 14398,
 29168,
 22461,
 13615,
 6360,
 40360,
 40182,
 31438,
 31798,
 14342,
 14385,
 14308,
 33841,
 12830,
 23096,
 34026,
 30835,
 15072,
 1121,
 18376,
 17815,
 32878,
 24410]

Напишите код для создания списка ингредиентов всех блюд, представленных в DataFrame. Результирующий список занесите в переменную ingredients.

In [63]:
ingredients = df.columns.tolist()[3:]
display(ingredients)

['cucumber',
 'ham hock',
 'dried rosemary',
 'chile powder',
 'fresh lime',
 'sugar',
 'ricotta',
 'Himalayan salt',
 'cardamom',
 'bell pepper',
 'nori',
 'dry vermouth',
 'mace',
 'plain whole-milk yogurt',
 'coconut',
 'whole milk ricotta cheese',
 'marshmallow creme',
 'semisweet chocolate',
 'pitted kalamata olives',
 'ras el hanout',
 'oil cured olives',
 'peanut sauce',
 'coriander',
 'ancho chile pepper',
 'mini cucumbers',
 'veal cutlets',
 'nonfat milk',
 'eau de vie',
 'jaggery',
 'kale',
 'frozen whole kernel corn',
 'greens',
 'goat cheese',
 'large egg whites',
 'chili paste',
 'taco sauce',
 'Old El Paso Flour Tortillas',
 'bertolli vineyard premium collect marinara with burgundi wine sauc',
 'Shaoxing wine',
 'tuna fillets',
 'wheat bran',
 'grilled chicken breasts',
 'serrano ham',
 'szechwan peppercorns',
 'lime',
 'dill',
 'champagne vinegar',
 'Turkish bay leaves',
 'mixed spice',
 'peeled tomatoes',
 'pickled jalapeno peppers',
 'bok choy',
 'tamarind',
 'confectioners sugar',
 'chestnut flour',
 'corn starch',
 'store bought low sodium chicken stock',
 'smoked paprika',
 'kiwi',
 'whipping cream',
 'back bacon rashers',
 'pimentos',
 'romaine lettuce',
 'thai green curry paste',
 'canola oil',
 'crawfish',
 'stuffing',
 'star anise',
 'balsamic vinegar',
 'rice noodles',
 'green beans',
 'bread',
 'luke warm water',
 'wheat germ',
 'cheese ravioli',
 'garlic powder',
 'pickles',
 'bosc pears',
 'ricotta cheese',
 'coarse salt',
 'cremini mushrooms',
 'fat skimmed chicken broth',
 'light brown muscavado sugar',
 'sunflower oil',
 'chicken breasts',
 'chicken',
 'penne',
 'chili oil',
 'soppressata',
 'fat-free refried beans',
 'epazote',
 'country ham',
 'dried cherry',
 'dried shiitake mushrooms',
 'pasta sauce',
 'dried basil',
 'golden delicious apples',
 'orange juice concentrate',
 'lasagne',
 'dried bonito flakes',
 'ground flaxseed',
 'wasabi',
 'prepared horseradish',
 'extra large eggs',
 'wheat',
 'lasagna noodles',
 'sweet paprika',
 'dri leav thyme',
 'sirloin tip roast',
 'ground beef',
 '1% low-fat milk',
 'hazelnut oil',
 'ciabatta',
 'dashi kombu',
 'ketchup',
 'arborio rice',
 'pita bread rounds',
 'grated parmesan cheese',
 'mandarin oranges',
 'branzino fillets',
 'crushed garlic',
 'couscous',
 'caster',
 'egg yolks',
 'soft fresh goat cheese',
 'cinnamon graham crackers',
 'bread crumb fresh',
 'egg noodles',
 'white sandwich bread',
 'Tabasco Pepper Sauce',
 'vanilla lowfat yogurt',
 'ground nutmeg',
 'louisiana hot sauce',
 'green cardamom pods',
 'portabello mushroom',
 'cheese slices',
 'white radish',
 'margarita salt',
 'rice vinegar',
 'seasoned rice wine vinegar',
 'swiss cheese',
 'yellow crookneck squash',
 'olive oil flavored cooking spray',
 'baking potatoes',
 'chopped walnuts',
 'saltines',
 'boneless chop pork',
 'quail',
 'applewood smoked bacon',
 'cracked black pepper',
 'frozen broad beans',
 'ground lamb',
 'basmati rice',
 'semolina',
 'top round steak',
 'chopped nuts',
 'dinner rolls',
 'fire roasted diced tomatoes',
 'fresh coriander',
 'fennel',
 'vegetable juice',
 'ricotta salata',
 'hot red pepper flakes',
 'fruit',
 'beef',
 'asiago',
 'anchovy fillets',
 'mustard oil',
 'lean ground pork',
 'active dry yeast',
 'taco seasoning',
 'chunky salsa',
 'light soy sauce',
 'eggs',
 'Italian parsley leaves',
 'garbanzo beans',
 'smoked streaky bacon',
 'hominy',
 'shredded lettuce',
 'sundried tomato paste',
 'celery salt',
 'ramps',
 'arame',
 'guajillo',
 'jam',
 'safflower oil',
 'roasted red peppers',
 'flax seed meal',
 'clams',
 'mushroom powder',
 'vegetable oil',
 'spinach leaves',
 'half & half',
 'organic sugar',
 'Flora Cuisine',
 'moong dal',
 'sweet pepper',
 'Japanese soy sauce',
 'vermicelli',
 'sesame oil',
 'dried chile',
 'bread slices',
 'granny smith apples',
 'bone-in chicken breasts',
 'bread crumbs',
 'ground cinnamon',
 'dijon mustard',
 'bamboo shoots',
 'rubbed sage',
 'ground chicken',
 'chicken cutlets',
 'whole milk',
 'boiling potatoes',
 'peppercorns',
 'basil leaves',
 'sliced black olives',
 'grape tomatoes',
 'crushed red pepper',
 'boneless skinless chicken breast halves',
 'lean steak',
 'tuna',
 'taco seasoning mix',
 'hot chili',
 'thai chile',
 'Sriracha',
 'jumbo shrimp',
 'dry mustard',
 'chicken drumsticks',
 'baby carrots',
 'sun-dried tomatoes in oil',
 'grated orange peel',
 'dried chickpeas',
 'haricots verts',
 'shell-on shrimp',
 'vegetable oil cooking spray',
 'kasuri methi',
 'white vinegar',
 'allspice berries',
 'dried chile peppers',
 'dry bread crumbs',
 'boneless chicken breast',
 'kahlГєa',
 'chickpea flour',
 'dried oregano',
 'fenugreek seeds',
 'fresh thyme leaves',
 'pork',
 'black mustard seeds',
 'crema mexicana',
 'vegan margarine',
 'vidalia',
 'ground allspice',
 'spareribs',
 'italian seasoning mix',
 'yellow peppers',
 'crab meat',
 'hot water',
 'garlic chili sauce',
 'chocolate covered coffee beans',
 'pickled carrots',
 'lower sodium soy sauce',
 'chile pepper',
 'lettuce',
 'watercress',
 'pecorino cheese',
 'sliced mushrooms',
 'red wine vinegar',
 'dried currants',
 'gnocchi',
 'crГЁme fraГ®che',
 'meat bones',
 'freshly ground pepper',
 'all-purpose flour',
 'leg of lamb',
 'straw mushrooms',
 'guacamole',
 'Johnsonville Andouille Dinner Sausage',
 'chickpeas',
 'starchy potatoes',
 'dried red chile peppers',
 'green peas',
 'noodles',
 'pesto',
 'adobo sauce',
 'linguine',
 'soba',
 'SargentoВ® Traditional Cut Shredded Mozzarella Cheese',
 'erythritol',
 'ancho powder',
 'water chestnuts',
 'chicken livers',
 'chipotle chile',
 'pickled jalapenos',
 'table cream',
 'fried garlic',
 'curry powder',
 'pork shoulder',
 'cannellini beans',
 'chives',
 'white wine vinegar',
 'pepperoni',
 'milk',
 'chicken legs',
 'mexican chorizo',
 'dried dillweed',
 'green chilies',
 'club soda',
 'trout fillet',
 'large eggs',
 'kimchi',
 'parsnips',
 'andouille sausage links',
 'molasses',
 'miso paste',
 'cabbage',
 'boneless skinless chicken breasts',
 'boneless skinless chicken',
 'sesame salt',
 'natural yogurt',
 'grating cheese',
 'serrano',
 'red beans',
 'creamy peanut butter',
 'manchego cheese',
 'peanut butter',
 'chile sauce',
 'asian pear',
 '(    oz.) tomato sauce',
 'long grain white rice',
 'Italian seasoned breadcrumbs',
 'jicama',
 'white bread',
 'french bread',
 'crushed tomatoes',
 'rock sugar',
 'mint',
 'hazelnuts',
 'red enchilada sauce',
 'mozzarella balls',
 'smoked ham hocks',
 'garam masala',
 'fennel bulb',
 'food colouring',
 'mascarpone',
 'butter lettuce',
 'yellow corn meal',
 'short rib',
 'chestnuts',
 'fenugreek',
 'instant espresso powder',
 'aioli',
 'barley',
 'romano cheese',
 'urad dal',
 'veal chops',
 'coconut sugar',
 'porcini',
 'brie cheese',
 'baby spinach leaves',
 'fontina',
 'mustard greens',
 'chicken stock',
 'garlic salt',
 'instant white rice',
 'water chestnuts, drained and chopped',
 'quinoa',
 'pizza crust',
 'plum tomatoes',
 'shredded Monterey Jack cheese',
 'shredded cabbage',
 'roasted peanuts',
 'Gochujang base',
 'pinenuts',
 'ground meat',
 'Philadelphia Cream Cheese',
 'swiss chard',
 'Madeira',
 'dark rum',
 'double-acting baking powder',
 'pork ribs',
 'wood ear mushrooms',
 'orzo pasta',
 'tamarind pulp',
 'pecan halves',
 'corn kernels',
 'dark brown sugar',
 'brown sugar',
 'vine ripened tomatoes',
 'chicken bouillon',
 'baking powder',
 'chile paste',
 'glass noodles',
 'boiling water',
 'sweet potatoes',
 'egg bread',
 'shrimp and crab boil seasoning',
 'italian salad dressing mix',
 'Taiwanese bok choy',
 'green chile',
 'enchilada sauce',
 'Mexican beer',
 'fry mix',
 'stock',
 'mushrooms',
 'hoisin sauce',
 'greek yogurt',
 'serrano chile',
 'red pepper flakes',
 'chipotle chile powder',
 'ground white pepper',
 'thyme',
 'chili flakes',
 'sauce',
 'broiler-fryer chicken',
 'allspice',
 'cumin',
 'lo mein noodles',
 'chinese cabbage',
 'florets',
 'unsweetened cocoa powder',
 'fresh red chili',
 'boneless chicken thighs',
 'solid pack pumpkin',
 'fresh lime juice',
 'matcha green tea powder',
 'pitted olives',
 'cooked rice',
 'fettucine',
 'pecans',
 'cheddar cheese',
 'fresh rosemary',
 'worcestershire sauce',
 'fresh veget',
 'fresh tarragon',
 'chicken breast halves',
 'sherry',
 'evaporated milk',
 'chopped pecans',
 'capers',
 'medjool date',
 'vegetables',
 'fat-free cottage cheese',
 'green cardamom',
 'sourdough',
 'steamed white rice',
 'tomato paste',
 'annatto oil',
 'gari',
 'black bean sauce',
 'sambal ulek',
 'red bell pepper',
 'cauliflower flowerets',
 'palm sugar',
 'kaffir lime leaves',
 'lower sodium chicken broth',
 'salsa',
 'old bay seasoning',
 'powdered sugar',
 'bay leaves',
 'sesame paste',
 'cumin seed',
 'orzo',
 'dry red wine',
 'grate lime peel',
 'gluten-free tamari',
 'yellow squash',
 'refrigerated piecrusts',
 'apple cider',
 'red radishes',
 'red chili powder',
 'buttermilk',
 'spicy brown mustard',
 'kale leaves',
 'saffron',
 'kashmiri chile',
 'cooked brown rice',
 'sweet cherries',
 'potatoes',
 'parsley',
 'extra firm tofu',
 'chipotle',
 'cane sugar',
 'whole kernel corn, drain',
 'beansprouts',
 'water',
 'pearl barley',
 'dashi',
 'olive oil cooking spray',
 'brown mustard seeds',
 'cake flour',
 'finely chopped fresh parsley',
 'golden brown sugar',
 'seasoned bread crumbs',
 'cracker crumbs',
 'fat',
 'low-fat sour cream',
 'coconut cream',
 'pasta',
 'BertolliВ® Classico Olive Oil',
 'white sugar',
 'lemon olive oil',
 'cream cheese, soften',
 'garlic paste',
 'dark soy sauce',
 'spinach',
 'green pepper',
 'raisins',
 'jack cheese',
 'fish sauce',
 'Italian bread',
 'zucchini',
 'fresh asparagus',
 'tomatoes',
 'lard',
 'glutinous rice flour',
 'grated orange',
 'boneless pork loin',
 'blackberries',
 'galangal',
 'softened butter',
 'baking apples',
 'arrowroot powder',
 'part-skim ricotta cheese',
 'pears',
 'condensed cream of chicken soup',
 'fresh ginger',
 'boneless rib eye steaks',
 'egg roll wraps',
 'baby bok choy',
 'seasoning salt',
 'gingerroot',
 'bread flour',
 'red miso',
 'smoked trout',
 'asparagus',
 'grated lemon zest',
 'cooking oil',
 'coconut milk',
 'tahini',
 'wasabi paste',
 'fat-free mayonnaise',
 'fresh mushrooms',
 'basil pesto sauce',
 'apple cider vinegar',
 'crusty rolls',
 'frozen edamame beans',
 'bone in chicken thighs',
 'ground pepper',
 'salsa verde',
 'unsalted roasted peanuts',
 'large shrimp',
 'gingersnap',
 'sun-dried tomatoes',
 'hot sauce',
 'rose petals',
 'onion tops',
 'preserved lemon',
 'whole wheat pasta',
 'tomato sauce',
 'red cabbage',
 'ice',
 'string beans',
 'goji berries',
 'lemon curd',
 'unsalted butter',
 'orange',
 'ground ginger',
 'nonstick spray',
 'eggplant',
 'McCormick Parsley Flakes',
 'espresso',
 'reduced sodium soy sauce',
 'clove',
 'ham',
 'fresh parsley',
 'crusty bread',
 'granulated garlic',
 'nutmeg',
 'kefalotyri',
 'lime juice',
 'extra sharp cheddar cheese',
 'lemongrass',
 'tumeric',
 'unsalted dry roast peanuts',
 'daikon',
 'penne pasta',
 'ground coriander',
 'brown cardamom',
 'phyllo',
 'creole mustard',
 'rice paper',
 'sage leaves',
 'wonton wrappers',
 'yellow cake mix',
 'chinese five-spice powder',
 'short-grain rice',
 'grana padano',
 'fillets',
 'orange liqueur',
 'apricot preserves',
 'great northern beans',
 'broccolini',
 'non-fat sour cream',
 'lettuce leaves',
 'grated jack cheese',
 'chipotles in adobo',
 'low sodium chicken broth',
 'panko breadcrumbs',
 'chicken wings',
 'mustard',
 'flat leaf parsley',
 'finely chopped onion',
 'pork loin chops',
 'chopped cilantro fresh',
 'tofu',
 'karashi',
 'fresh basil',
 'fresh ginger root',
 'plain yogurt',
 'red lentils',
 'pork chops',
 'condiments',
 'lamb',
 'apples',
 'lemon',
 'kalamata',
 'oregano',
 'red chile powder',
 'parmigiano reggiano cheese',
 'burger buns',
 'parmesan cheese',
 'carrots',
 'filet',
 'seafood seasoning',
 'polenta',
 'baby arugula',
 'fat free cream cheese',
 'sliced chicken',
 'skim milk',
 'berries',
 'penne rigate',
 'grouper',
 'wakame',
 'seasoning',
 'oyster sauce',
 'orange zest',
 'yellow mustard',
 'cactus pad',
 'artichokes',
 'dough',
 'rum extract',
 'rhubarb',
 'golden raisins',
 'lemon slices',
 'Fuyu persimmons',
 'chiles',
 'sheepвЂ™s milk cheese',
 'grapeseed oil',
 'tapioca starch',
 'natural peanut butter',
 'onions',
 'chopped green chilies',
 'canned corn',
 'cooked quinoa',
 'roasted salted cashews',
 'torn romain lettuc leav',
 'chili pepper',
 'mixed greens',
 'kidney beans',
 'membrillo',
 'potato starch',
 'curry',
 'salad',
 'beer',
 'free range egg',
 'white almond bark',
 'lean ground beef',
 'firmly packed brown sugar',
 'peanut oil',
 'paprika',
 'Crystal Farms Shredded Gouda Cheese',
 'reduced fat milk',
 'green peppercorns',
 'corn flour',
 'frozen blueberries',
 'cooked shrimp',
 'chicken leg quarters',
 'butter',
 'green onions',
 'jasmine rice',
 'part-skim mozzarella cheese',
 'bean paste',
 'dry white wine',
 'oven-ready lasagna noodles',
 'chinese noodles',
 'marshmallows',
 'low-fat buttermilk',
 'fat free less sodium chicken broth',
 'demerara sugar',
 'cashew nuts',
 'pico de gallo',
 'beef shank',
 'corn syrup',
 'coconut flour',
 'green bell pepper, slice',
 'crema',
 'shredded mozzarella cheese',
 'rice cakes',
 'tamari soy sauce',
 'sourdough loaf',
 'fish fillets',
 'maida flour',
 'hamburger buns',
 'red pepper',
 'fresh parmesan cheese',
 'grapefruit juice',
 'boiled ham',
 'beef stock',
 'beef rib short',
 'corn tortillas',
 'tomato purГ©e',
 'fresh lemon juice',
 'naan',
 'garlic cloves',
 'lemon grass',
 'whole nutmegs',
 'rosemary leaves',
 'pasta rotel',
 'salted roast peanuts',
 'toasted pecans',
 'white rice',
 'catfish fillets',
 'horseradish',
 'pumpkin purГ©e',
 'blueberri preserv',
 'honey',
 'cider vinegar',
 'plain breadcrumbs',
 'shortening',
 'sherry vinegar',
 'peaches',
 'bittersweet chocolate',
 'condensed cheddar cheese soup',
 'roma tomatoes',
 'duck fat',
 'chopped tomatoes',
 'black peppercorns',
 'rolls',
 'poblano chiles',
 'cheese',
 'savoy cabbage',
 'refried beans',
 'superfine sugar',
 'calimyrna figs',
 'grated nutmeg',
 'english muffins, split and toasted',
 'broccoli rabe',
 'mango',
 'freshly grated parmesan',
 'soba noodles',
 'asian fish sauce',
 'garlic puree',
 'steak',
 'ice cubes',
 'pistachio nuts',
 'dark sesame oil',
 'leaves',
 'chili garlic paste',
 'lump crab meat',
 'fresh herbs',
 'fresh tomatoes',
 'sprinkles',
 'reduced sodium chicken broth',
 'tortilla chips',
 'peeled fresh ginger',
 'cinnamon sugar',
 'chili powder',
 'cayenne',
 'lemon juice',
 'cream of tartar',
 'lentils',
 'double cream',
 'Mexican cheese',
 'cinnamon',
 'frozen spinach',
 'spaghetti',
 'genoa salami',
 'lamb neck fillets',
 'strawberries',
 'turnips',
 'condensed cream of mushroom soup',
 'feta cheese',
 'curry leaves',
 'lime wedges',
 'chicken bones',
 'lemon soda',
 'mustard powder',
 'cherry tomatoes',
 'vidalia onion',
 'reduced sodium tamari',
 'fat free yogurt',
 'caramel sauce',
 'figs',
 'parsley leaves',
 'cream',
 'low sodium soy sauce',
 'coleslaw',
 'skirt steak',
 'baguette',
 'dried mint flakes',
 'creole seasoning',
 'edamame',
 'low-fat mayonnaise',
 'thai basil',
 'baby potatoes',
 'pistachios',
 'black beans',
 'gruyere cheese',
 'skinless chicken breasts',
 'vinaigrette dressing',
 'plantains',
 'instant butterscotch pudding mix',
 'bacon slices',
 'scallions',
 'silken tofu',
 'pork loin',
 'vegetable broth',
 'toasted sesame oil',
 'heavy whipping cream',
 'napa cabbage leaves',
 'fresh salmon',
 'basil',
 'capicola',
 'sausage casings',
 'amchur',
 'canned black beans',
 'fingerling potatoes',
 'pineapple juice',
 'wide rice noodles',
 'white cornmeal',
 'pitas',
 'baking soda',
 'rosemary sprigs',
 'spring onions',
 'chili',
 'hibiscus',
 'giardiniera',
 'english cucumber',
 'tequila',
 'spam',
 'snow peas',
 'octopuses',
 'seaweed',
 'pasta water',
 'marinara sauce',
 'bacon, crisp-cooked and crumbled',
 'almond extract',
 'fresh pineapple',
 'chillies',
 'extra-lean ground beef',
 'bay leaf',
 'capsicum',
 'summer squash',
 'candied orange peel',
 'chuck roast',
 'margarita mix',
 'granulated sugar',
 'almonds',
 'yukon gold potatoes',
 'aged gouda',
 'fresh raspberries',
 'chinese chives',
 'diced celery',
 'sea scallops',
 'beans',
 'chees fresco queso',
 'dried porcini mushrooms',
 'picante sauce',
 'canned low sodium chicken broth',
 'oysters',
 'fresh thyme',
 'shiso',
 'whole wheat flour',
 'kecap manis',
 'coriander powder',
 'okra',
 'chunky peanut butter',
 'vinegar',
 'fenugreek leaves',
 'flour',
 'tomato ketchup',
 'organic chicken',
 'bird chile',
 'white wine',
 'cooking wine',
 'collard greens',
 'chopped celery',
 'chopped green bell pepper',
 'minced beef',
 'low-fat natural yogurt',
 'coarse sea salt',
 'vanilla extract',
 'rib eye steaks',
 'heavy cream',
 'low-fat milk',
 'monterey jack',
 'medium eggs',
 'persian cucumber',
 'frozen peas',
 'bourbon whiskey',
 'white miso',
 'navy beans',
 'chopped fresh sage',
 'butternut squash',
 'fresh dill',
 'maple syrup',
 'oil',
 'fresh oregano',
 'cooked ham',
 'California bay leaves',
 'colby cheese',
 'lime zest',
 'russet potatoes',
 'pork shoulder roast',
 'cod',
 'frozen pastry puff sheets',
 'warm water',
 'coffee beans',
 'rice syrup',
 'jambalaya rice mix',
 'yoghurt',
 'sweet and sour sauce',
 'chorizo',
 'green tomatoes',
 'anise',
 'pasilla pepper',
 'tamarind paste',
 'pepper',
 'dried kidney beans',
 'plain flour',
 'green papaya',
 'red wine',
 'pound cake',
 'Thai fish sauce',
 'tortillas',
 'dressing',
 'mozzarella cheese',
 'chicken tenderloin',
 'buckwheat noodles',
 'frozen whipped topping',
 'Pillsburyв„ў Refrigerated Crescent Dinner Rolls',
 'self rising flour',
 'ginger',
 'fresh lemon',
 'ground cloves',
 'pickapeppa sauce',
 'cauliflower',
 'fat free milk',
 'fresh spinach',
 'Old El Pasoв„ў mild red enchilada sauce',
 'piloncillo',
 'toasted cashews',
 'cayenne pepper',
 'lemon zest',
 'black olives',
 'arugula',
 'italian seasoning',
 'rice wine',
 'cornflour',
 'kosher salt',
 'white corn tortillas',
 'celery',
 'sweet onion',
 'coconut vinegar',
 'chili paste with garlic',
 'lemon cucumber',
 'cooked chicken',
 'button mushrooms',
 'tea bags',
 'chipotle peppers',
 'provolone cheese',
 'red beets',
 'chili sauce',
 'onion powder',
 'flank steak',
 'sweetened condensed milk',
 'orange bell pepper',
 'zesty italian dressing',
 'white onion',
 'red chili peppers',
 'barbecue sauce',
 'red kidney beans',
 'leeks',
 'coarse kosher salt',
 'salmon steaks',
 'wish bone guacamol ranch dress',
 'Crystal Farms Butter',
 'chopped cilantro',
 'garlic',
 'hot pepper sauce',
 ...]

Теперь мы можем использовать подготовленные списки ids и ingredients для непосредственного создания JSON-структуры.

После десериализации JSON-файла мы получили структуру, представляющую собой список, состоящий из словарей. Каждый словарь состоял из трёх пар "ключ-значение", при этом в качестве значений выступали:

целое число (id блюда);
строковая величина (тип кухни);
список строковых величин (перечень ингредиентов).
Сейчас нам предстоит воссоздать эту структуру, извлекая данные из DataFrame. Для этого необходимо создать:

пустой список new_recipes — для хранения итоговой структуры;
используя код из Задачи 7.1, список ids — для хранения id всех блюд;
используя код из Задачи 7.2, список ingredients — для хранения названий всех ингредиентов.

In [67]:
# Написать код функции make_list(), которая принимает на вход строку DataFrame df, содержащую полные данные об одном блюде (в виде Series), и возвращает перечень ингредиентов, входящих в состав этого блюда (в виде списка)
def make_list(df_row):
    result_list = []
    for ing_name in ingredients:
        if df_row[ing_name].iloc[0] == 1:
            result_list.append(ing_name)
    return result_list

In [69]:
# Создаём пустой список для хранения итоговой структуры
new_recipes = []
# Организуем цикл с параметром current_id
for current_id in ids:
    # Получаем значение соответствующей кухни, применив фильтр по текущему значению параметра цикла к DataFrame;
    cuisine = df[df['id'] == current_id]['cuisine'].iloc[0]
    # Получаем перечень ингредиентов, входящих в состав текущего блюда
    current_ingredients = make_list(df[df['id'] == current_id])
    # Создаём текущий словарь
    current_recipe = {'cuisine': cuisine, 'id': int(current_id), 'ingredients': current_ingredients}
    # Добавляем созданный словарь к списку
    new_recipes.append(current_recipe)

display(new_recipes)

[{'cuisine': 'greek',
  'id': 10259,
  'ingredients': ['romaine lettuce',
   'garbanzo beans',
   'grape tomatoes',
   'seasoning',
   'pepper',
   'black olives',
   'garlic',
   'feta cheese crumbles',
   'purple onion']},
 {'cuisine': 'southern_us',
  'id': 25693,
  'ingredients': ['eggs',
   'vegetable oil',
   'milk',
   'yellow corn meal',
   'thyme',
   'tomatoes',
   'ground pepper',
   'green tomatoes',
   'plain flour',
   'ground black pepper',
   'salt']},
 {'cuisine': 'filipino',
  'id': 20130,
  'ingredients': ['grilled chicken breasts',
   'garlic powder',
   'eggs',
   'chicken livers',
   'green chilies',
   'cooking oil',
   'butter',
   'pepper',
   'yellow onion',
   'salt',
   'soy sauce',
   'mayonaise']},
 {'cuisine': 'indian',
  'id': 22213,
  'ingredients': ['wheat', 'vegetable oil', 'water', 'salt']},
 {'cuisine': 'indian',
  'id': 13162,
  'ingredients': ['milk',
   'natural yogurt',
   'garam masala',
   'water',
   'garlic paste',
   'onions',
   'butter',
   'chili powder',
   'lemon juice',
   'double cream',
   'bay leaf',
   'oil',
   'cayenne pepper',
   'cornflour',
   'passata',
   'salt',
   'shallots',
   'black pepper',
   'ground cumin',
   'boneless chicken skinless thigh']},
 {'cuisine': 'jamaican',
  'id': 6602,
  'ingredients': ['sugar',
   'eggs',
   'ground cinnamon',
   'milk',
   'baking powder',
   'powdered sugar',
   'ground ginger',
   'fresh ginger root',
   'butter',
   'vanilla extract',
   'plain flour',
   'salt']},
 {'cuisine': 'spanish',
  'id': 42779,
  'ingredients': ['white vinegar',
   'flat leaf parsley',
   'skirt steak',
   'bay leaf',
   'pepper',
   'chopped cilantro',
   'garlic',
   'chorizo sausage',
   'medium shrimp',
   'jalapeno chilies',
   'sea salt',
   'salt',
   'olive oil']},
 {'cuisine': 'italian',
  'id': 3735,
  'ingredients': ['sugar',
   'eggs',
   'baking powder',
   'white almond bark',
   'pistachio nuts',
   'almond extract',
   'flour',
   'vanilla extract',
   'dried cranberries',
   'olive oil']},
 {'cuisine': 'mexican',
  'id': 16903,
  'ingredients': ['lime',
   'pork',
   'cheddar cheese',
   'chopped cilantro fresh',
   'corn tortillas',
   'fresh pineapple',
   'purple onion',
   'iceberg lettuce',
   'jalapeno chilies',
   'ground black pepper',
   'salt',
   'olive oil',
   'poblano peppers']},
 {'cuisine': 'italian',
  'id': 12734,
  'ingredients': ['flat leaf parsley',
   'fresh basil',
   'chopped tomatoes',
   'kosher salt',
   'garlic',
   'extra-virgin olive oil']},
 {'cuisine': 'italian',
  'id': 5875,
  'ingredients': ['pimentos',
   'canola oil',
   'swiss cheese',
   'sweet pepper',
   'dried oregano',
   'mushrooms',
   'pepper',
   'black olives',
   'provolone cheese',
   'garlic',
   'sharp cheddar cheese',
   'olive oil',
   'sausages']},
 {'cuisine': 'chinese',
  'id': 45887,
  'ingredients': ['sugar',
   'Shaoxing wine',
   'corn starch',
   'canola oil',
   'green beans',
   'sesame oil',
   'dry mustard',
   'water',
   'fresh ginger',
   'low sodium soy sauce',
   'scallions',
   'garlic',
   'white pepper',
   'ground turkey',
   'crushed red pepper flakes']},
 {'cuisine': 'italian',
  'id': 2698,
  'ingredients': ['hot red pepper flakes',
   'Italian parsley leaves',
   'chipotle chile',
   'trout fillet',
   'flat leaf parsley',
   'fresh lemon juice',
   'garlic cloves',
   'fine sea salt',
   'walnuts',
   'extra-virgin olive oil']},
 {'cuisine': 'mexican',
  'id': 41995,
  'ingredients': ['ground cinnamon',
   'plum tomatoes',
   'lime juice',
   'ground coriander',
   'onions',
   'chili powder',
   'kosher salt',
   'flank steak',
   'garlic',
   'ground black pepper',
   'salt',
   'black pepper',
   'fresh cilantro',
   'olive oil',
   'ground cumin',
   'avocado',
   'crushed red pepper flakes']},
 {'cuisine': 'italian',
  'id': 31908,
  'ingredients': ['gnocchi',
   'all-purpose flour',
   'butter',
   'fat free less sodium chicken broth',
   'fresh parmesan cheese',
   'gruyere cheese',
   'bacon slices',
   'fat free milk',
   'ground black pepper',
   'cooking spray',
   'salt',
   'chopped fresh chives']},
 {'cuisine': 'indian',
  'id': 24717,
  'ingredients': ['garam masala',
   'sweet potatoes',
   'spinach',
   'tomatoes',
   'tumeric',
   'red lentils',
   'onions',
   'naan',
   'red chili peppers',
   'vegetable stock']},
 {'cuisine': 'british',
  'id': 34466,
  'ingredients': ['confectioners sugar',
   'greek yogurt',
   'lemon curd',
   'raspberries']},
 {'cuisine': 'italian',
  'id': 1420,
  'ingredients': ['broiler-fryer chicken',
   'italian seasoning',
   'zesty italian dressing',
   'mayonaise']},
 {'cuisine': 'thai',
  'id': 2941,
  'ingredients': ['sugar', 'hot chili', 'lime juice', 'asian fish sauce']},
 {'cuisine': 'vietnamese',
  'id': 8152,
  'ingredients': ['corn starch',
   'chicken breasts',
   'vegetable oil',
   'garlic chili sauce',
   'fresh lime juice',
   'cooked rice',
   'red bell pepper',
   'yellow squash',
   'broccolini',
   'sliced green onions',
   'salt',
   'soy sauce',
   'chicken broth']},
 {'cuisine': 'thai',
  'id': 13121,
  'ingredients': ['rice noodles',
   'creamy peanut butter',
   'roasted peanuts',
   'hoisin sauce',
   'beansprouts',
   'water',
   'chopped cilantro fresh',
   'thai basil',
   'pork loin',
   'chopped fresh mint',
   'medium shrimp',
   'rice']},
 {'cuisine': 'mexican',
  'id': 40523,
  'ingredients': ['lime',
   'roma tomatoes',
   'kosher salt',
   'chopped cilantro',
   'purple onion',
   'jalapeno chilies']},
 {'cuisine': 'southern_us',
  'id': 40989,
  'ingredients': ['baking potatoes',
   'eggs',
   'spicy brown mustard',
   'low-fat mayonnaise',
   'pepper',
   'salt']},
 {'cuisine': 'chinese',
  'id': 29630,
  'ingredients': ['sesame oil',
   'yellow peppers',
   'extra firm tofu',
   'water',
   'arrowroot powder',
   'fresh ginger',
   'red pepper',
   'orange bell pepper',
   'sesame seeds',
   'soy sauce',
   'broccoli',
   'red curry paste']},
 {'cuisine': 'italian',
  'id': 49136,
  'ingredients': ['linguine',
   'capers',
   'flat leaf parsley',
   'marinara sauce',
   'lemon zest',
   'garlic',
   'olives',
   'olive oil',
   'crushed red pepper flakes']},
 {'cuisine': 'chinese',
  'id': 26705,
  'ingredients': ['sugar',
   'light soy sauce',
   'sesame oil',
   'chives',
   'cabbage',
   'lo mein noodles',
   'beansprouts',
   'dark soy sauce',
   'oyster sauce',
   'pepper',
   'flank steak',
   'salt',
   'peanuts',
   'dried black mushrooms',
   'chicken broth']},
 {'cuisine': 'cajun_creole',
  'id': 27976,
  'ingredients': ['chile pepper',
   'stock',
   'onions',
   'paprika',
   'mango',
   'fresh tomatoes',
   'lemon juice',
   'oil',
   'red chili peppers',
   'herbs']},
 {'cuisine': 'italian',
  'id': 22087,
  'ingredients': ['grated parmesan cheese',
   'sliced mushrooms',
   'all-purpose flour',
   'sherry',
   'butter',
   'spaghetti',
   'heavy cream',
   'cooked chicken',
   'ground black pepper',
   'salt',
   'chicken broth']},
 {'cuisine': 'chinese',
  'id': 9197,
  'ingredients': ['corn starch',
   'vegetable oil',
   'molasses',
   'shredded cabbage',
   'fresh ginger root',
   'carrots',
   'onions',
   'oil',
   'sweet and sour sauce',
   'garlic',
   'soy sauce',
   'green bell pepper',
   'ground pork',
   'egg roll wrappers']},
 {'cuisine': 'mexican',
  'id': 1299,
  'ingredients': ['large eggs',
   'cheese',
   'breakfast sausages',
   'flour tortillas']},
 {'cuisine': 'italian',
  'id': 40429,
  'ingredients': ['yellow corn meal',
   'boiling water',
   'butter',
   'fresh parmesan cheese',
   'sea salt']},
 {'cuisine': 'cajun_creole',
  'id': 34419,
  'ingredients': ['chicken breasts',
   'all-purpose flour',
   'red bell pepper',
   'potatoes',
   'hot sauce',
   'fresh parsley',
   'onions',
   'peanut oil',
   'garlic cloves',
   'celery',
   'shrimp',
   'cajun seasoning',
   'andouille sausage',
   'bacon',
   'chicken broth',
   'ground red pepper']},
 {'cuisine': 'mexican',
  'id': 10276,
  'ingredients': ['garlic powder',
   'dried oregano',
   'paprika',
   'chili powder',
   'onion powder',
   'ground black pepper',
   'sea salt',
   'ground cumin',
   'crushed red pepper flakes']},
 {'cuisine': 'thai',
  'id': 33465,
  'ingredients': ['chile powder',
   'eggs',
   'vegetable oil',
   'roasted peanuts',
   'palm sugar',
   'beansprouts',
   'fish sauce',
   'sliced chicken',
   'garlic cloves',
   'turnips',
   'lime wedges',
   'chinese chives',
   'tamarind paste',
   'green papaya',
   'ground black pepper',
   'shallots',
   'firm tofu']},
 {'cuisine': 'italian',
  'id': 39250,
  'ingredients': ['dried basil',
   'crushed garlic',
   'dried oregano',
   'white sugar',
   'onions',
   'green onions',
   'diced tomatoes',
   'olive oil']},
 {'cuisine': 'cajun_creole',
  'id': 37963,
  'ingredients': ['Johnsonville Andouille Dinner Sausage',
   'worcestershire sauce',
   'parsley',
   'creole seasoning',
   'jambalaya rice mix',
   'hot pepper sauce',
   'shrimp',
   'diced tomatoes',
   'olive oil']},
 {'cuisine': 'italian',
  'id': 20051,
  'ingredients': ['bread slices',
   'sage leaves',
   'great northern beans',
   'garlic cloves',
   'pepper',
   'shrimp',
   'salt',
   'olive oil']},
 {'cuisine': 'filipino',
  'id': 11300,
  'ingredients': ['sugar',
   'star anise',
   'crushed garlic',
   'cooking oil',
   'chinese five-spice powder',
   'ground black pepper',
   'chicken thighs',
   'salt',
   'soy sauce',
   'chicken broth']},
 {'cuisine': 'southern_us',
  'id': 17610,
  'ingredients': ['green onions',
   'garlic cloves',
   'tortilla chips',
   'chili powder',
   'cayenne pepper',
   'shredded cheddar cheese',
   'cream cheese',
   'black-eyed peas']},
 {'cuisine': 'southern_us',
  'id': 37405,
  'ingredients': ['ham hock',
   'chile powder',
   'freshly ground pepper',
   'chicken stock',
   'bay leaves',
   'apple cider',
   'onions',
   'collard greens',
   'cayenne pepper',
   'salt',
   'rib',
   'extra-virgin olive oil',
   'large garlic cloves',
   'light brown sugar']},
 {'cuisine': 'italian',
  'id': 28302,
  'ingredients': ['pepperoni',
   'butter',
   'giardiniera',
   'mozzarella cheese',
   'italian seasoning',
   'hoagie rolls',
   'salami',
   'Oscar Mayer Deli Fresh Smoked Ham']},
 {'cuisine': 'brazilian',
  'id': 31634,
  'ingredients': ['lime', 'club soda', 'ice cubes', 'turbinado', 'white rum']},
 {'cuisine': 'mexican',
  'id': 32304,
  'ingredients': ['canola oil',
   'shredded lettuce',
   'enchilada sauce',
   'green pepper',
   'corn tortillas',
   'garlic cloves',
   'canned black beans',
   'picante sauce',
   'cooked chicken',
   'sliced green onions',
   'sour cream',
   'shredded cheddar cheese']},
 {'cuisine': 'indian',
  'id': 36341,
  'ingredients': ['vegetable oil',
   'curry powder',
   'serrano chile',
   'sauce',
   'cumin seed',
   'fresh ginger',
   'salt',
   'shallots',
   'fresh cilantro',
   'salmon fillets']},
 {'cuisine': 'mexican',
  'id': 29369,
  'ingredients': ['vegetable oil',
   'white vinegar',
   'chicken breast halves',
   'tomatoes',
   'lettuce leaves',
   'chopped cilantro fresh',
   'chopped onion',
   'jalapeno chilies',
   'salt',
   'black pepper',
   'avocado']},
 {'cuisine': 'chinese',
  'id': 27564,
  'ingredients': ['mandarin oranges',
   'eggs',
   'vegetable oil',
   'water',
   'white sugar',
   'yellow cake mix',
   'orange liqueur',
   'frosting']},
 {'cuisine': 'french',
  'id': 18515,
  'ingredients': ['sugar',
   'fennel bulb',
   'water',
   'lemon olive oil',
   'grapefruit juice',
   'salt']},
 {'cuisine': 'southern_us',
  'id': 3335,
  'ingredients': ['sugar',
   'vegetable oil',
   'all-purpose flour',
   'baking powder',
   'buttermilk',
   'onions',
   'white cornmeal',
   'bacon drippings']},
 {'cuisine': 'southern_us',
  'id': 4499,
  'ingredients': ['crawfish',
   'old bay seasoning',
   'butter',
   'garlic',
   'salt',
   'cream cheese',
   'crab boil']},
 {'cuisine': 'southern_us',
  'id': 4906,
  'ingredients': ['white vinegar',
   'white sugar',
   'lemon juice',
   'ground black pepper',
   'salt',
   'mayonaise']},
 {'cuisine': 'japanese',
  'id': 5767,
  'ingredients': ['sugar',
   'glass noodles',
   'water',
   'green onions',
   'low sodium soy sauce',
   'yellow onion',
   'sake',
   'corn oil',
   'napa cabbage',
   'shiitake',
   'sirloin',
   'mirin']},
 {'cuisine': 'southern_us',
  'id': 30748,
  'ingredients': ['whipping cream',
   'large eggs',
   'worcestershire sauce',
   'hot sauce',
   'extra sharp cheddar cheese',
   'monterey jack',
   'quickcooking grits',
   'ground black pepper',
   'chicken broth',
   'ground red pepper']},
 {'cuisine': 'italian',
  'id': 35930,
  'ingredients': ['crushed red pepper',
   'linguine',
   'bay leaves',
   'tomatoes',
   'flat leaf parsley',
   'finely chopped onion',
   'fresh basil',
   'dry white wine',
   'garlic cloves',
   'basil',
   'salt',
   'black pepper',
   'olive oil',
   'mussels']},
 {'cuisine': 'southern_us',
  'id': 44902,
  'ingredients': ['sugar',
   'all-purpose flour',
   'large eggs',
   'yellow corn meal',
   'buttermilk',
   'unsalted butter',
   'honey',
   'baking soda',
   'corn oil',
   'salt']},
 {'cuisine': 'italian',
  'id': 31119,
  'ingredients': ['pesto', 'lemon', 'white wine', 'salmon fillets']},
 {'cuisine': 'jamaican',
  'id': 3535,
  'ingredients': ['ground beef',
   'bread crumbs',
   'white vinegar',
   'all-purpose flour',
   'curry powder',
   'large eggs',
   'allspice',
   'worcestershire sauce',
   'bay leaves',
   'unsalted butter',
   'curry',
   'fresh thyme',
   'pepper',
   'pickapeppa sauce',
   'cayenne pepper',
   'kosher salt',
   'onion powder',
   'garlic',
   'yellow onion',
   'extra-virgin olive oil',
   'low sodium beef broth',
   'cold water']},
 {'cuisine': 'japanese',
  'id': 47028,
  'ingredients': ['chopped walnuts',
   'eggs',
   'all-purpose flour',
   'milk',
   'baking powder',
   'matcha green tea powder',
   'white sugar',
   'melted butter',
   'salt']},
 {'cuisine': 'indian',
  'id': 38112,
  'ingredients': ['coarse salt',
   'vegetable oil',
   'fenugreek',
   'urad dal',
   'potatoes',
   'white rice']},
 {'cuisine': 'italian',
  'id': 2646,
  'ingredients': ['pesto',
   'pizza crust',
   'plum tomatoes',
   'part-skim mozzarella cheese']},
 {'cuisine': 'irish',
  'id': 5206,
  'ingredients': ['1% low-fat milk',
   'low-fat sour cream',
   'yukon gold potatoes',
   'leeks',
   'cooking spray',
   'salt',
   'black pepper',
   'olive oil']},
 {'cuisine': 'thai',
  'id': 38233,
  'ingredients': ['sugar',
   'fish sauce',
   'cooking oil',
   'garlic',
   'chicken thighs',
   'black pepper']},
 {'cuisine': 'thai',
  'id': 39267,
  'ingredients': ['peanut sauce',
   'sesame oil',
   'spareribs',
   'boiling water',
   'golden brown sugar',
   'fresh ginger',
   'lemongrass',
   'tamari soy sauce',
   'unsweetened coconut milk',
   'dry sherry',
   'large garlic cloves',
   'rice']},
 {'cuisine': 'indian',
  'id': 11913,
  'ingredients': ['vegetable oil',
   'chile pepper',
   'chicken legs',
   'garam masala',
   'tomato paste',
   'cumin seed',
   'water',
   'tomatoes',
   'chopped cilantro fresh',
   'fresh ginger root',
   'onions',
   'garlic',
   'ghee',
   'ground turmeric']},
 {'cuisine': 'jamaican',
  'id': 20591,
  'ingredients': ['cracked black pepper',
   'bread crumbs',
   'curry powder',
   'stock',
   'water',
   'tomatoes',
   'tumeric',
   'onions',
   'paprika',
   'butter',
   'chillies',
   'minced beef',
   'oil',
   'plain flour',
   'ginger',
   'celery',
   'garlic',
   'salt',
   'dried thyme',
   'cold water']},
 {'cuisine': 'italian',
  'id': 70,
  'ingredients': ['crushed tomatoes',
   'fresh rosemary',
   'boneless pork loin',
   'onions',
   'kosher salt',
   'garlic',
   'ground black pepper',
   'olive oil',
   'pappardelle']},
 {'cuisine': 'thai',
  'id': 43928,
  'ingredients': ['vegetable oil',
   'red bell pepper',
   'extra firm tofu',
   'coconut milk',
   'eggplant',
   'fresh basil',
   'onions',
   'red curry paste']},
 {'cuisine': 'korean',
  'id': 8530,
  'ingredients': ['sugar',
   'rice vinegar',
   'top round steak',
   'sesame oil',
   'Gochujang base',
   'Taiwanese bok choy',
   'beansprouts',
   'carrots',
   'jasmine rice',
   'scallions',
   'garlic',
   'sesame seeds',
   'shiitake',
   'soy sauce']},
 {'cuisine': 'french',
  'id': 275,
  'ingredients': ['sugar',
   'corn starch',
   'milk',
   'large egg yolks',
   'vanilla']},
 {'cuisine': 'french',
  'id': 43769,
  'ingredients': ['marshmallow creme',
   'orange juice concentrate',
   'ground nutmeg',
   'ground cinnamon',
   'gingersnap',
   'toasted pecans',
   'pumpkin purГ©e',
   'maple syrup',
   'cream cheese']},
 {'cuisine': 'southern_us',
  'id': 49111,
  'ingredients': ['green beans',
   'white vinegar',
   'brown sugar',
   'white sugar',
   'bacon',
   'salt',
   'black pepper']},
 {'cuisine': 'spanish',
  'id': 11886,
  'ingredients': ['serrano ham',
   'dijon mustard',
   'large eggs',
   'manchego cheese',
   'sourdough',
   'membrillo',
   'butter']},
 {'cuisine': 'indian',
  'id': 45839,
  'ingredients': ['greens',
   'ground flaxseed',
   'Sriracha',
   'chickpea flour',
   'chickpeas',
   'curry powder',
   'spinach',
   'tahini',
   'panko breadcrumbs',
   'burger buns',
   'carrots',
   'onions',
   'garlic cloves',
   'chili powder',
   'lemon juice',
   'scallions',
   'pepper',
   'salt',
   'soy sauce',
   'fresh cilantro',
   'olive oil',
   'ground cumin']},
 {'cuisine': 'moroccan',
  'id': 699,
  'ingredients': ['ground cinnamon',
   'ground ginger',
   'ground coriander',
   'whole nutmegs',
   'ground cloves',
   'ground black pepper',
   'ground cumin',
   'ground cardamom']},
 {'cuisine': 'italian',
  'id': 24568,
  'ingredients': ['balsamic vinegar',
   'Italian bread',
   'tomatoes',
   'fresh basil',
   'onions',
   'red pepper',
   'garlic',
   'olive oil']},
 {'cuisine': 'italian',
  'id': 8820,
  'ingredients': ['grated parmesan cheese',
   'roasted red peppers',
   'penne pasta',
   'shredded mozzarella cheese',
   'honey',
   'sausage casings',
   'kosher salt',
   'garlic',
   'ground black pepper',
   'olive oil',
   'crushed red pepper flakes']},
 {'cuisine': 'moroccan',
  'id': 16582,
  'ingredients': ['chickpeas',
   'chicken stock',
   'tomato paste',
   'saffron',
   'tomatoes',
   'fresh ginger',
   'fresh parsley',
   'tumeric',
   'lemon',
   'flour',
   'warm water',
   'pepper',
   'salt',
   'shallots',
   'fresh cilantro',
   'olive oil']},
 {'cuisine': 'moroccan',
  'id': 9058,
  'ingredients': ['pitted kalamata olives',
   'fat skimmed chicken broth',
   'couscous',
   'tomato paste',
   'fat',
   'ground pepper',
   'preserved lemon',
   'chopped cilantro fresh',
   'onions',
   'paprika',
   'cayenne',
   'garlic',
   'ground turmeric',
   'salt',
   'diced tomatoes',
   'harissa',
   'ground cardamom']},
 {'cuisine': 'vietnamese',
  'id': 4715,
  'ingredients': ['ice', 'espresso', 'sweetened condensed milk']},
 {'cuisine': 'japanese',
  'id': 29061,
  'ingredients': ['top round steak',
   'vegetable oil',
   'fresh asparagus',
   'green onions',
   'shiitake',
   'soy sauce']},
 {'cuisine': 'mexican',
  'id': 2107,
  'ingredients': ['green chilies',
   'plum tomatoes',
   'finely chopped onion',
   'chopped cilantro fresh',
   'jalapeno chilies',
   'avocado']},
 {'cuisine': 'cajun_creole',
  'id': 22825,
  'ingredients': ['watercress',
   'pecans',
   'golden brown sugar',
   'onions',
   'hamburger buns',
   'fresh lemon juice',
   'garlic cloves',
   'creole seasoning',
   'hot pepper sauce',
   'andouille sausage',
   'okra pods',
   'ground black pepper',
   'salt',
   'olive oil',
   'crumbled blue cheese',
   'chuck',
   'mayonaise']},
 {'cuisine': 'southern_us',
  'id': 13758,
  'ingredients': ['sugar',
   'confectioners sugar',
   'eggs',
   'milk',
   'food colouring',
   'softened butter',
   'butter',
   'self rising flour',
   'vanilla']},
 {'cuisine': 'french',

Выполним сериализацию списка new_recipes и запишем полученные данные в файл.

Для сериализации  используем функцию dumps(), которой в качестве параметра передадим список new_recipes. Запись в файл осуществляется с помощью метода write(). Предварительно файл необходимо открыть для записи с помощью функции open() c параметром 'w' (от англ. write, рус. писать):

In [70]:
# Импорт модуля json
import json
# Функция dumps() модуля json сериализирует объект Python в строку формата JSON.
new_recipes = json.dumps(new_recipes)

# Откроем файл new_recipes.json для записи
with open("data/new_recipes.json", "w") as write_file:
    # Записываем содержимое подготовленные данные в файл
    write_file.write(new_recipes)

ИЗВЛЕКАЕМ КОНТЕНТ ИЗ XML-ФАЙЛА

In [74]:
tree = ET.parse('data/menu.xml')

КОРЕНЬ

In [79]:
root = tree.getroot()
display(root)
display(type(root))
# Для того чтобы посмотреть список потомков корневого узла, выполним следующий код:
display(list(root))
# Для того чтобы получить список потомков второго блюда в нашем меню и вывести его на экран, выполним код:
display(list(root[1]))
# Выведем на экран атрибуты первого блюда из меню:
display(root[0].attrib)

xml.etree.ElementTree.Element

[<Element 'price' at 0x11bf052b0>,
 <Element 'weight' at 0x11bf04310>,
 <Element 'class' at 0x11bf07ba0>]

{'name': 'Кура'}

В XML-узлах часто хранятся количественные показатели. Эти показатели хранятся в виде текста, и прочитать их можно, обратившись к атрибуту text у соответствующего объекта типа ElementTree.Element.

Например, возьмём узел price первого блюда из меню:

In [80]:
display(root[0][0].text)

'40'

In [82]:
# Если вы хотите прочитать наименование тега конкретного узла, необходимо использовать tag. Например, получим наименование тега корневого узла:
display(root[0][2].tag)

'class'

Используя цикл for, автоматизируем обход дерева. Для этого напишем следующий код:

In [83]:
for dish in root:
    for param in dish:
        print(dish.attrib['name'], param.tag, param.text)
    print()

Кура price 40
Кура weight 300
Кура class Мясо

Греча price 20
Греча weight 200
Греча class Крупа

ЗАГРУЖАЕМ ДАННЫЕ ИЗ XML-ФАЙЛА В DATAFRAME

Реализуем следующий алгоритм:

Загрузить данные из XML-файла menu.xml в переменную root.
Создать пустой список df_list (в него будем добавлять строчки итоговой таблицы).
Заранее создать список column_names с именами столбцов — название блюда (name), его цена (price), вес (weight) и класс (class).
В цикле организовать обход xml-дерева из корня по всем потомкам.
На каждой итерации цикла сформировать в виде списка строку таблицы, содержащую информацию: наименование блюда (атрибут name узла dish) и значения потомков этого узла — узлов price, weight, class.
Добавить сформированную строку в список df_list, используя метод append().
Сформировать из вложенного списка DataFrame. Имена для столбцов взять из списка column_names.

In [84]:
column_names = ['name', 'price', 'weight', 'class']
df_list = []

for dish in root:
    row = [dish.attrib['name'], dish[0].text, dish[1].text, dish[2].text]
    df_list.append(row)

df = pd.DataFrame(df_list, columns=column_names)
display(df)

    name price weight  class
0   Кура    40    300   Мясо
1  Греча    20    200  Крупа

СОЗДАЁМ XML-ФАЙЛ

In [86]:
# Чтобы создать корень дерева, используем метод Element() из класса ElementTree:
new_root = ET.Element('menu')
display(new_root)

Теперь мы можем добавлять новые узлы в наше дерево, используя метод SubElement() из того же класса.

Добавим в наше меню двух потомков корневого узла, которые будут представлять два блюда, то есть будут узлами dish:

In [87]:
dish1 = ET.SubElement(new_root, 'dish', name='Кура')

dish2 = ET.SubElement(new_root, 'dish', name='Греча')

display(list(new_root))

Добавим в создаваемую структуру по три потомка (атрибута) к двум новым узлам, которые будут содержать информацию о блюде — о его цене (price), весе (weight) и классе (class), а также значение этих атрибутов:

In [88]:
price1 = ET.SubElement(dish1, "price").text = "40"
weight1 = ET.SubElement(dish1, "weight").text = "300"
class1 = ET.SubElement(dish1, "class").text = "Мясо"
display(list(dish1))

price2 = ET.SubElement(dish2, "price").text = "20"
weight2 = ET.SubElement(dish2, "weight").text = "200"
class2 = ET.SubElement(dish2, "class").text = "Крупа"
display(list(dish2))

[<Element 'price' at 0x139d8c900>,
 <Element 'weight' at 0x139d8da80>,
 <Element 'class' at 0x139d8c220>]

[<Element 'price' at 0x10e283970>,
 <Element 'weight' at 0x11a679fd0>,
 <Element 'class' at 0x139d8cf40>]

Проверим визуально корректность созданной нами структуры, выполнив фрагмент кода, разработанного ранее:

In [89]:
for dish in new_root:
    for param in dish:
        print(dish.attrib['name'], param.tag, param.text)
    print()

Кура price 40
Кура weight 300
Кура class Мясо

Греча price 20
Греча weight 200
Греча class Крупа

СОХРАНЕНИЕ XML-ФАЙЛА

In [90]:
new_root_string = ET.tostring(new_root)

with open("new_menu.xml", "wb") as f:
    f.write(new_root_string)

In [91]:
ET.ElementTree(new_root).write('new_menu_good.xml', encoding="utf-8")