In [12]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble
from sklearn.model_selection import train_test_split

In [3]:
wine_data = pd.read_csv('data/winequality-red.csv', sep=';')
wine_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
wine_data['quality'] = wine_data['quality'].apply(lambda x: 1 if x>=6 else 0)
wine_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0

In [5]:
X = wine_data.drop('quality', axis=1)
y = wine_data['quality']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
rf_clf_wine = ensemble.RandomForestClassifier(
    n_estimators=500,
    max_depth=8,
    min_samples_leaf=10,
    criterion='gini',
    max_features='sqrt',
    random_state=42
)
rf_clf_wine.fit(X_train, y_train)

y_pred = rf_clf_wine.predict(X_train)
y_pred_test = rf_clf_wine.predict(X_test)

print(f'train accuracy: {np.round(rf_clf_wine.score(X_train, y_train), 2)}')
print(f'test accuracy: {np.round(metrics.accuracy_score(y_test, y_pred_test), 2)}')

train accuracy: 0.85
test accuracy: 0.75